### ISSUE TITLE
Mixer custom CRDs deprecation plan

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#12773]
- [x] update samples and e2e tests to use standard Mixer CRDs https://github.com/istio/istio/pull/12689
- [x] update documentation to refer to standard Mixer CRDs https://istio.io/help/ops/telemetry/missing-metrics/#verify-mixer-metric-instances-configuration-exists https://github.com/istio/istio.io/issues/3851
- [x] delete old style CRDs https://github.com/istio/istio/pull/12710
- [x] backport to support migration from 1.1 with standard CRDs https://github.com/istio/istio/pull/12815
- [x] add a flag to disable listening to template CRDs (adapter CRD flag is already present and flipped) https://github.com/istio/istio/pull/12851
- [x] update Galley to be lenient about presence of Mixer custom CRDs #12822 
- [x] update Galley/Mixer to validate standard Mixer CRDs https://github.com/istio/istio/issues/12886

More items:
- [x] announce deprecation of old style CRDs
- [x] make sure new charts do not use old style CRDs https://github.com/istio-ecosystem/istio-installer/pull/84
- [x] update validation tool to work on new style CRDs https://github.com/istio/istio/pull/13379
- [ ] print warning for deprecated config in `istioctl validate`

/assign @kyessenov

**Comment by bianpengyuan** [comment]
Do we also want to add some deprecation log into galley or mixer?

**Comment by kyessenov** [comment]
@bianpengyuan We're thinking to add istioctl command to support automatic conversion. We can probably indicate deprecation warning in the tool then. Logging has a risk of log pollution.

**Comment by kyessenov** [comment]
More items:
- [ ] announce deprecation of old style CRDs
- [ ] make sure new charts do not use old style CRDs
- [ ] update validation tool to work on new style CRDs

**Comment by kyessenov** [comment]
Announced the plan to deprecate in WG and on discuss https://discuss.istio.io/t/deprecation-notice-custom-mixer-adapter-crds/2055

**Comment by kyessenov** [comment]
Deprecation warnings should be covered as part of https://github.com/istio/istio/issues/10746.
We need a general mechanism for warning about API deprecations across istio, not just for Mixer custom CRDs.
