### ISSUE TITLE
RBAC Integration Tests Tracker 

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#14213]
- [x] Authorization for HTTP Services (#13384, #13925)
- [x] Authorization for TCP Services (#13384, #13925)
- [x] Authorization for gRPC Services
- [x] Authorization for groups and list claims. PR:  https://github.com/istio/istio/pull/13557, https://github.com/istio/istio/pull/13628.
- [ ] Authorization permissive mode

**Comment by liminw** [comment]
Thanks @pitlv2109 for creating the issue. 

@yangminzhu @pitlv2109 @lei-tang If the integration tests are already completed, could you check the corresponding item above, and added a PR link next to it? Thanks!

**Comment by lei-tang** [comment]
For "Authorization for groups and list claims", the PR are: https://github.com/istio/istio/pull/13557, https://github.com/istio/istio/pull/13628.

**Comment by yangminzhu** [comment]
Adding RBAC test for path with double dots: https://github.com/istio/istio/pull/14184
