### ISSUE TITLE
[Istio Auto mTLS] Simplify our mTLS user experience

### ISSUE THREAD

**Issue by linsun** [istio/istio#14524]
Updated 0920/2019 by @incfly 

Tasks breakdown

- [x] Done, Introduce mesh config API to control the Auto mTLS feature. All the changes below assumes this flag is set to true.
- [x] WIP, Change API default behavior when server side authn policy is `STRICT`, no need to configure client side DestinationRule. https://github.com/istio/istio/issues/16586
- [x] Actual implementation of auto mTLS in Pilot, https://github.com/istio/istio/pull/16296
- [x] WIP Release qualification testing with large loads of endpoints, https://github.com/istio/istio/issues/16866
- [ ] `istioctl` tooling allows customers to switch from `PERMISSIVE` to `STRICT` easily, https://github.com/istio/istio/issues/16867
- [ ] Per deployment opt-in annotations support for migration, https://github.com/istio/istio/issues/17276
- [ ] Documentation.
- [ ] Audit multi cluster and mesh expansion tooling changes.

---

Original Description.

Today when a user needs to secure communication among services, user needs to ensure an auth policy is set on the target service along with strict mTLS configuration in destination rule.  This process is non intuitive and very error prune.   There is a desire to simplify this, especially when comparing with other service mesh projects out there that have a much better UX experience.  Could we just have 1 profile (vs strict mTLS and permissive mTLS 2 profiles in 1.1) where we always do mTLS for services within the mesh by default?

A few items that we should experiment as part of the work to start with:

1) detect if a service is part of the mesh or not part of the mesh using annotation 

2) don’t register the service not in the mesh in the registry.  confirm mTLS for services within mesh and non-mTLS for services reaching out to other services in k8s or external services (when no service entry is configured with allow_any) 

note: https://github.com/istio/istio/issues/14435 is introduced to help users to quickly test things in and out of mesh.

**Comment by ianstanton** [comment]
I have a few questions that I thought I'd drop here as I'm starting to get a bit confused by the current `mTLS` user experience:

* In the helm chart there is an option to enable / disable `mTLS` https://github.com/istio/istio/blob/bd7e445fd7b980a7b94b32ab155c1d27c886cabf/install/kubernetes/helm/istio/values.yaml#L300-L303.
  * With `mtls.enabled false` we have sidecar injection and plain text traffic (health check) is allowed.
    * We also see the following in the mesh policy:
        ```
        spec:
            peers:
            - mtls:
                mode: PERMISSIVE
        ```
    * Is this the equivalent of `PERMISSIVE mTLS` mode?

  * With `mtls.enabled true`, we have sidecar injection but plain text traffic (health check) is NOT allowed.
    * We also see the following in the mesh policy:
      ```
      spec:
        peers:
        - mtls: {}
      ```
    * Is this the equivalent of `STRICT mTLS` mode? According to [this post](https://discuss.istio.io/t/istio-1-0-6-set-mtls-mode-to-strict-from-helm/1067), it is.

* While in `PERMISSIVE mTLS` mode, can we assume that our pods with sidecars are communicating with mTLS while also allowing plain text traffic?

Thanks for your help, and let me know if this belongs elsewhere!

**Comment by linsun** [comment]
@ianstanton 

1. yes, that is correct, for permission mTLS.
2. I think so, I would appreciate if @wattli can correct me if I'm wrong.  I normally do permissive mode and enable mTLS strict from auth policy and destination rule.
3. It will try mTLS first then if it fails, plain text traffic will be used (instead of fail the communication).

**Comment by ianstanton** [comment]
@linsun Thanks for the explanation! This definitely helps me understand the concepts better. Is there a good way to visualize this communication with something like logs or Kiali?

**Comment by jmazzitelli** [comment]
> Is there a good way to visualize this communication with something like logs or Kiali?

You can definitely see mTLS settings visualized in Kiali. You will get visualized hints when comms have mTLS enabled or disabled. Here are a couple Kiali PRs that have screen shots:

https://github.com/kiali/kiali-ui/pull/1089

https://github.com/kiali/kiali-ui/pull/963

**Comment by lucasponce** [comment]
cc @xeviknal

**Comment by xeviknal** [comment]
@ianstanton I have an unofficial video regarding the mtls on Kiali: https://www.youtube.com/watch?v=GnjwaTcNKK4 Perhaps it can help.

**Comment by louiscryan** [comment]
See

https://github.com/envoyproxy/envoy/issues/7135

**Comment by ianstanton** [comment]
@jmazzitelli @lucasponce @xeviknal @louiscryan Super helpful - I really appreciate all of your help!

**Comment by wattli** [comment]
@incfly @diemtvu

**Comment by yangminzhu** [comment]
cc @yangminzhu

**Comment by incfly** [comment]
Summary of the current status

The [design doc](https://docs.google.com/document/d/1yEMDRO2FZCyZnDK1AzNmjQtbtQqE7wN8YoM65FAH7uA/edit#) analyzes the API improvements and proposed one mechanism of having Pilot tracking the endpoints label, so that configure the client outbound cluster TLS configuration automatically when all server endpoints having envoy sidecar.

Some other alternative, by adding features in Envoy to configure TLS configuration as per endpoint basis, is also being explored. See relevant [Envoy Github issue](https://github.com/envoyproxy/envoy/issues/8016).

Summary of status quo and some facts as of 08/30

- We have a WIP PR for the proposal, https://github.com/istio/istio/pull/16296
- Envoy FR is still in design phase.
- Istio 1.4 release is cut in **5.5 weeks**.

Given that, with discussion to relevant folks, we're proposing following execution plan

- Continue giving the best shot we can for Envoy design. If we are able to get it in within **2 weeks** we use it for Istio 1.4
- If not, we go for the existing the pilot autopilot approach.
- To reduce the amount of work potentially wasted, we split https://github.com/istio/istio/pull/16296 into two part, modifying sidecar injector labels and propagating endpoints labels. And the rest follow-up PR depends on which direction to go.
- We're continue to working on simplifying `STRICT` mode and setup performance measurements, they're needed regardless which approach to take.

/cc @rshriram @diemtvu @GregHanson @costinm @linsun  
please chime in, thanks.

**Comment by incfly** [comment]
Action item, resolving comment here about label in EDS memory footprint, @

**Comment by incfly** [comment]
Action item, need to double check if the `envoy::api::v2::core::TransportSocket` uses `Any::typed_config` or `Struct::config` matters for performance.

Theoretically they should both work from the code base that I can tell

**Comment by incfly** [comment]
One more thing to verify after feature complete

Our grafana dashboard w.r.t mTLS is still showing correct data. Currently it's referencing the mixer attribute `connection.mtls`. This attribute is set via mixer [filter](https://github.com/istio/proxy/blob/master/src/envoy/tcp/mixer/filter.cc#L201). At the connection level.

Our new approach, per endpoint mTLS, will still work, since per connection level data structure does not change.

**Comment by incfly** [comment]
Action item, ensure the transport_socket_matches `total_match_count` is not dropped by default. I didn't see this during development (15000/stats), suspect our bootstrap drop the metrics...

**Comment by incfly** [comment]
Action item, currently client sidecar does not have mTLS metrics, we need to add that. DOWNSTREAM access log also need to be changed to include mTLS information.

**Comment by incfly** [comment]
Action item, stats is not available either, we need first extend Envoy API to check whether local certificate is requested, (some debates on the PR), https://github.com/envoyproxy/envoy/pull/8621

Then plumb-in the API to [wasm filter API](https://sourcegraph.com/github.com/envoyproxy/envoy-wasm@16a5cdbf450e4d3bbeead962af5c29bc002ce8b7/-/blob/source/extensions/filters/common/expr/context.cc), such that Mixer V2 is able to report to telemetry dashboard.
