### ISSUE TITLE
[Tracker] Support trustworthy JWTs when SDS is enabled.

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#15709]
This is to track trustworthy JWTs for SDS. 

- [ ] Only enable k8s jwt authenticator when SDS is enabled.
- [ ] Only allow trustworthy JWTs by default when SDS is enabled.
- [ ] Find gap for trustworthy JWTs support in different vendors and update installation/task doc accordingly.
- [ ] Support trustworthy JWTs in KinD.
- [ ] Update security integration test(s) to use trustworthy JWTs.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
