### ISSUE TITLE
Container Build enhancements

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#16334]
A few things to improve in the build-tools container image:

- [x] Stuff we install into the image should be pinned to specific versions. The Ruby and Nodejs binaries we pull in currently are not pinned.

- [x] The nodejs installation appears incomplete. When building targets in istio.io, there is a zillion messages that fly by about stuff being downloaded on the fly before anything happens. This didn't used to be the case using the website-tools container, so it's new behavior. It slows the build process down considerably and breaks the air-gap build property we want.

- [x] Ruby gems should be installed with the --no-document option to avoid pulling in extra stuff.

- [x] Nodejs components should be installed with the --production option to avoid pulling in strictly dev-time dependencies

**Comment by howardjohn** [comment]
Is most of this done? Seems a lot changed quickly

If we are throwing in possible improvements though

* Get autocompletion to work (`make <TAB>` no longer works)
* Get .PHONY to work
* Find a way to easily run ad-hoc commands in the docker container. It would be cool to do something like `builder go test ./pilot/proxy/pkg -run MyTest` and have it run in docker. Otherwise I (and I assume others) will need to maintain the same dev environment as the builder tools, since I do a lot of ad-hoc commands
* Maybe a `make shell` command that just runs the docker contain in bash? If the above is done then this is obsolete though

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/17483
https://github.com/istio/istio/issues/17476
https://github.com/istio/istio/issues/17475
https://github.com/istio/istio/issues/17474
