### ISSUE TITLE
Golang 1.13 support

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16635]
Changes: https://tip.golang.org/doc/go1.13

This issue tracks any changes needed to support building and releasing based on golang 1.13. This will be out fairly soon, but I couldn't find an exact date.

## Progress
* [x] `go1.13rc1 build -v ./...`
* [x] `go1.13rc1 test -v ./...`
  * [x] TestCompiledExpressions Mixer test - fixed by https://github.com/istio/istio/pull/16709
  * [x] binaries-test - fixed by https://github.com/istio/istio/pull/16638
  * [x] `go1.13rc1 test -race ./istioctl/cmd/...` broken with `panic: cannot deep copy *v1alpha3.ServiceEntry` (turned out to not be a go 1.13 issue, fixed in https://github.com/istio/istio/pull/16708)
* [x] `go1.13rc1 test -v -race ./...`
* [x] Build and deploy images to real cluster
* [x] Binaries have correct version output
  * [x] Broken -  `version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.13rc1", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}`. Fixed by https://github.com/istio/istio/pull/16723
* [x] ~~Builds still use vendor~~
  * ~~Need to pass `-mod=vendor` explicitly. Will fix this only if we don't remove vendor by then~~
  * ~~Will be obsolete by https://github.com/istio/istio/pull/16668~~
* [x] Native integration tests pass

## TODO
* [x] Update istio builder (in tools repo)
* [x] Update istio builder (in prow repo) https://github.com/istio/test-infra/pull/1788
* [x] Disable GODEBUG or wait for fix from https://github.com/golang/go/issues/32952. disabled in https://github.com/istio/istio/pull/16852

## Enhacements using go 1.13
* [x] `go build -o` to build all targets at once -- more efficient than building targets as multiple commands. My benchmarks show 6s/1s in 1.13 (new/cached) vs 37s/8s in 1.12: https://github.com/istio/istio/pull/17153
* [x] `-trimpath` for reproducible builds https://github.com/istio/istio/pull/17213

**Comment by howardjohn** [comment]
Some mixer tests break:
```
2019-08-28T23:11:31.294829Z     warn    compiler.Compile failed. expr:'ab + bb', err:'internal compiler error -- Add for type not yet implemented: bool'
--- FAIL: TestCompiledExpressions (0.02s)
    --- FAIL: TestCompiledExpressions/Compiled/email(as)#01 (0.00s)
        expressionbuilder_test.go:66: evaluation error mismatch: 'error converting 'barfoo' to e-mail: 'mail: missing '@' or angle-addr'' != 'error converting 'barfoo' to e-mail: 'mail: no angle-addr''
FAIL
FAIL    istio.io/istio/mixer/pkg/lang/compiled  0.114s
2019-08-28T23:11:31.223726Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.223784Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.224445Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.224782Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225067Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225108Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225251Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225287Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225325Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225465Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225606Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225906Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.225997Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.229860Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.230001Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.230140Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.236856Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.236903Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.236944Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.237624Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.237660Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.237703Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.238567Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.243480Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.243668Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.251196Z     warn    internal compiler error -- Add for type not yet implemented: [bool]
2019-08-28T23:11:31.251214Z     warn    compiler.Compile failed. expr:'ab + bb', err:'internal compiler error -- Add for type not yet implemented: bool'
--- FAIL: TestCompiler_SingleExpressionSession (0.03s)
    compiler_test.go:81: evaluation error mismatch: 'error converting 'barfoo' to e-mail: 'mail: missing '@' or angle-addr'' != 'error converting 'barfoo' to e-mail: 'mail: no angle-addr''
2019-08-28T23:11:31.251647Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.251661Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.251701Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.251711Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.252219Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.252232Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.252966Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.252985Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253364Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253377Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253419Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253429Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253618Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253628Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253667Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253676Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253716Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253727Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253888Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.253899Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.254026Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.254037Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.254377Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.254389Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.254487Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.254497Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.262062Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.262085Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.262122Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.262131Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.262173Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.262184Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.265732Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.265759Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.265803Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.265820Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.265871Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.266867Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.266885Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.266925Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.266937Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.266987Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.267002Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.268186Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.268204Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.274548Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.274566Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.274692Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.274701Z     warn    interpreter.Result: Unknown type encountered. Returning nil. type: 'unknown'
2019-08-28T23:11:31.283534Z     warn    internal compiler error -- Add for type not yet implemented: [bool]
2019-08-28T23:11:31.283557Z     warn    compiler.Compile failed. expr:'ab + bb', err:'internal compiler error -- Add for type not yet implemented: bool'
--- FAIL: TestCompiler_DoubleExpressionSession (0.03s)
    compiler_test.go:126: evaluation error mismatch: 'error converting 'barfoo' to e-mail: 'mail: missing '@' or angle-addr'' != 'error converting 'barfoo' to e-mail: 'mail: no angle-addr''
2019-08-28T23:11:31.304895Z     warn    internal compiler error -- Add for type not yet implemented: [bool]
2019-08-28T23:11:31.304939Z     warn    compiler.Compile failed. expr:'ab + bb', err:'internal compiler error -- Add for type not yet implemented: bool'
--- FAIL: TestCompile (0.02s)
    --- FAIL: TestCompile/124_'email(as)' (0.00s)
        compiler_test.go:221: expected error not found: E:'error converting 'barfoo' to e-mail: 'mail: no angle-addr'', A:'error converting 'barfoo' to e-mail: 'mail: missing '@' or angle-addr''
FAIL
```

**Comment by howardjohn** [comment]
`make binaries-test` is also broken

```
$ go1.13rc1 test ./tests/binary/... -v --base-dir /usr/local/google/home/howardjohn/go/out/linux_amd64/release --binaries="pilot-discovery pilot-agent sidecar-injector mixc mixs mixgen node_agent node_agent_k8s istio_ca istioctl galley sdsclient"
flag provided but not defined: -test.v
Usage of /tmp/go-build195510588/b001/binary.test:
  -base-dir string
        directory for binaries
  -binaries string
        space separated binaries to test
FAIL    istio.io/istio/tests/binary     0.051s
FAIL
```

**Comment by howardjohn** [comment]
#16801 was also related

**Comment by kyessenov** [comment]
Yeah, sounds good. The hard-coded errors were left there by @ozevren . I think we should not depend on the concrete error text.

**Comment by howardjohn** [comment]
We need to update golangci-lint: https://github.com/golangci/golangci-lint/releases/tag/v1.18.0

**Comment by howardjohn** [comment]
The last thing needed is to fix tests that use boskos which fail like https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16948/e2e-dashboard_istio/147. I think the problem is we run `go get istio.io/test-infra/boskos/cmd/mason_client` which tampers with the `go.mod` file and breaks the tests later

**Comment by howardjohn** [comment]
This is done!
