### ISSUE TITLE
RBAC v2 conversion tool tracker

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#18338]
- [ ] Documentation

**Convert ClusterRbacConfig to AuthorizationPolicy**

- [ ] Support mesh wide level (on, off)
- [ ] Support namespace level (on with inclusion, on with exclusion)
- [ ] Support service level

**Convert ServiceRole and ServiceRoleBinding to AuthorizationPolicy**

- [ ] Service name to workload selector
- [ ] * in service name
- [ ] * as prefix/suffix in service name
- [ ] One access rule per ServiceRole
- [ ] Multiple access rule per ServiceRole
- [ ] One subject per ServiceRoleBinding
- [ ] Multiple subjects per ServiceRoleBinding
- [ ] Constraints and properties to first class field 
- [ ] Move `group` in subject to Condition

**Comment by pitlv2109** [comment]
The majority of the work has been done. This is to track future improvements

**Comment by incfly** [comment]
Done? Feel free to reopen
