### ISSUE TITLE
Tracking: Authentication policy v1beta1

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#18399]
Design docs:
- [High level](https://docs.google.com/document/d/1CUm0UNpV85JQEwEbyrBxk058Bc8DuVkk9tOW_H0mxLc/edit#heading=h.23g9oybtucso)

- [JWT](https://docs.google.com/document/d/1f1ZVCUa7ktuoFKKFATCXfu9qFFFXX-7UMAJQtmMPuS4/edit#)

- [mTLS](https://docs.google.com/document/d/1RAsCl4n_F75ANAXrbI9tllA8QmE4etQ3HBHXNjxLPTo/edit#)

Tasks:

- [x] Add API for `RequestAuthentication`
- [X] Pilot: register new CRD for `RequestAuthentication` (https://github.com/istio/istio/pull/18949, https://github.com/istio/installer/pull/553)
- [X] Pilot: implement authN applier for `RequestAuthentication`(https://github.com/istio/istio/issues/19084)
- [x] Envoy: enhance JWT filter to support "allow missing but no-invalid token" mode (https://github.com/envoyproxy/envoy/issues/8909)
- <del>[ ] Envoy: replacement for `authn` filter. https://github.com/istio/istio/issues/19077</del>
- [x] Add API for `PeerAuthentication` (https://github.com/istio/api/pull/1241)
- [ ] Pilot: implement authN applier for `PeerAuthentiation` (https://github.com/istio/istio/issues/20746)
