### ISSUE TITLE
Move Envoy admin interface from TCP:15000 to a Unix Domain Socket

### ISSUE THREAD

**Issue by rlenglet** [istio/istio#19684]
**Bug description**

In each sidecar, the Envoy proxy in the `istio-proxy` container is currently configured to expose its [admin interface](https://www.envoyproxy.io/docs/envoy/latest/operations/admin) on [a TCP socket bound to the loopback interface](https://github.com/istio/istio/blob/78350cd2ae70174004a43ae8d194fcd548f75a1d/tools/packaging/common/envoy_bootstrap_v2.json#L182-L190) (by default, that port is 15000). That socket is accessible by any container within the pod, since they are in the same network namespace. Therefore, a malicious or compromised container may perform any admin operation on Envoy. Especially, it can [force Envoy to quit](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--quitquitquit), and therefore to continuously reconnect to Pilot, which can induce some load on Pilot, which in turn can affect the rest of the cluster.

**Expected behavior**

The admin interface should not be accessible outside of the `istio-proxy` container. The admin interface should be exposed as a Unix Domain Socket, local only to that container.

**Tasks**

- [ ] Modify [Envoy's bootstrap file template](https://github.com/istio/istio/blob/78350cd2ae70174004a43ae8d194fcd548f75a1d/tools/packaging/common/envoy_bootstrap_v2.json#L182-L190) to:
  - [ ] Always expose the admin interface as a Unix Domain Socket.
  - [ ] Optionally also expose the admin interface as a TCP socket, depending on a template parameter.
- [ ] Modify the `pilot-agent` to accept an additional boolean flag or environment variable to set the template parameter.
- [ ] Define and document a new boolean pod annotation to enable the admin TCP interface.
- [ ] Modify the injection template for both [Helm](https://github.com/istio/istio/blob/78350cd2ae70174004a43ae8d194fcd548f75a1d/install/kubernetes/helm/istio/files/injection-template.yaml#L84) and [Operator](https://github.com/istio/installer/blob/5305f02bb3076961ad352ba56da3f8686a2354e0/istio-control/istio-autoinject/files/injection-template.yaml#L89) to set that flag/variable depending on the pod's annotation. Default to `true` for Istio 1.5.
- [ ] Modify all dependencies on TCP port 15000 in the Istio code, esp. in the [`istio-agent request` command](https://github.com/istio/istio/blob/78350cd2ae70174004a43ae8d194fcd548f75a1d/pilot/cmd/pilot-agent/request.go#L36).
- [ ] Fix all remaining documentation pages that recommends to perform `curl` commands to port 15000, and replace them with calls to `istio-agent request` commands.
- [ ] Document the admin interface TCP socket as deprecated in 1.5, to be disabled by default in 1.6.

**Comment by rlenglet** [comment]
cc @howardjohn

**Comment by howardjohn** [comment]
This will probably break users, likely @Stono being one of them

**Comment by rlenglet** [comment]
I see. I suppose this is used by tricks to make Jobs work, or something like that?

Then I'd propose to make the move to UDS anyway, and support optionally exposing via TCP in addition to UDS if explicitly enabled by customer. How does that sound? @Stono?

**Comment by howardjohn** [comment]
Yeah, the quitting Envoy hacks are mostly solved by pilot agent exposing the quit endpoint. Not sure if there are other cases (that we should support)

**Comment by rlenglet** [comment]
Right, apart from the quitting Envoy, I don't see what features from the admin interface would be useful to an application container.

**Comment by howardjohn** [comment]
There are tools like scuttle and envoy-preflight that might, I forget if
they do that or make you share process namespace and look at the process
directly

**Comment by rlenglet** [comment]
Adding links to your references:

- [scuttle](https://github.com/redboxllc/scuttle)
- [envoy-preflight](https://github.com/monzo/envoy-preflight)

Both have the exact same description: "A wrapper for applications to help with running envoy as a sidecar."

**Comment by rlenglet** [comment]
It seems like both scuttle and envoy-preflight support using a UDS instead of the HTTP interface.

We could then mount the UDS in a volume shared among the containers within the same pod. I don't know how that could work with automatic injection though, because the application container would have to refer to a volume that is injected.

**Comment by Stono** [comment]
Hi this is correct, we use the http interface on pilot-agent to terminate the sidecar after the job container completes, currently we have 57 jobs deployed in this manner.

A better (less change inducing model for me) would be to have the http interface enabled by an annotation (so off by default), that way the jobs would continue to work as i could just annotate them with `sidecar.istio.io/httpAdminEndpoint: "true"`.  

When it comes to envoy-preflight, I think you're maybe being ambitious asking everyone using that on their day to day workloads to expose a shared volume between the sidecar and the application to facilitate a UDS interface.  I suppose that would be a trade off, between security and complexity.  In that scenario too; I'd suggest making it a decision of the operator with something like an annotation.

**Comment by ChenLingPeng** [comment]
We can insert an iptables rule to reject connection from the user whose UID/GID is not 1337, right?

**Comment by rlenglet** [comment]
> We can insert an iptables rule to reject connection from the user whose UID/GID is not 1337, right?

That wouldn't work. The hack to make Jobs work is to access the admin interface from within the application's container when it terminates. And application containers should not run with UID 1337, since they would bypass the proxy.

**Comment by rlenglet** [comment]
> A better (less change inducing model for me) would be to have the http interface enabled by an annotation (so off by default), that way the jobs would continue to work as i could just annotate them with sidecar.istio.io/httpAdminEndpoint: "true".

Agreed, that would be a good compromise. Anyway you need to modify those pods to make them work with the Istio sidecar.

**Comment by ChenLingPeng** [comment]
I mean in proxy-init container we can insert iptables rule to reject the connection to port 15000 from the process whose UID/GID is not 1337, so application container will be rejected to access 15000 port(since application containers should not run with UID 1337)

**Comment by Stono** [comment]
> > A better (less change inducing model for me) would be to have the http interface enabled by an annotation (so off by default), that way the jobs would continue to work as i could just annotate them with sidecar.istio.io/httpAdminEndpoint: "true".
> 
> Agreed, that would be a good compromise. Anyway you need to modify those pods to make them work with the Istio sidecar.

We do which makes this even more difficult to roll out actually.  Application deployments aren’t injected, pods are, which means they’re disconnected.  Therefore updating istio to a newer version will break live deployed services until they’re redeployed.

For me, this is a breaking change, the way to correctly roll it out would be 

1. Add the annotation but default to enabled
2. Give deprecation notice 
3. In future release change annotation default to false

**Comment by rlenglet** [comment]
> I mean in proxy-init container we can insert iptables rule to reject the connection to port 15000 from the process whose UID/GID is not 1337, so application container will be rejected to access 15000 port(since application containers should not run with UID 1337)

This wouldn't solve the problem. The hack to make Jobs work currently requires application containers (NOT running with UID 1337) to access port 15000 to kill Envoy when the job is complete. Blocking access to UIDs other than 1337 would break that hack.

**Comment by rlenglet** [comment]
There may be a way we can detect that a pod is derived from a Job? In which case we could enable TCP only for that case?

`istioctl kube-inject` could easily distinguish Jobs from other resources in https://github.com/istio/istio/blob/7a4fb65717fe578a86472beb860b113c364c2cff/pkg/kube/inject/inject.go#L744.

The automatic injector could also detect that a Pod is running a Job: the Pod's `metadata.ownerReferences.kind has value `Job` in this case.

**Comment by Stono** [comment]
It’s not just jobs... honestly, make it configurable and let the operator decide

**Comment by rlenglet** [comment]
@Stono 
I don't see any legitimate case other than Jobs?!
And to clarify my previous comment: I propose to make the default setting to enabling TCP to true only for Jobs, to make the transition easier for you. We'd still introduce the annotation to make this configurable.

**Comment by Stono** [comment]
I think I agree with you, I am just cautious that istio is in the wild, and you don’t know for sure how people are using the admin interface, without asking everyone.  

So it seems excessive and potentially breaking to try and add Job inference into the injector when you can simply make it an annotation/toggle and leave it to the operator to decide what they want to do, then deprecate it in a controlled fashion. 

Just my two cents 🤘

**Comment by howardjohn** [comment]
Agree with Karl, the less special cases (eg Jobs are different) the better

**Comment by rlenglet** [comment]
OK, sounds good. I updated the tasks in this PR's description. @Stono, @howardjohn please confirm that this works for you.

**Comment by Stono** [comment]
I found an example of where we use the admin interface to stop the sidecar, not in a Job.  [Airflow](https://airflow.apache.org): we run Airflow Scheduler on K8s which creates Pods, not Jobs (which get injected with sidecars) - which run to completion then stop the sidecar. 

```
❯ k -n data-platform-airflow get pods
NAME                                                                                                   READY   STATUS    RESTARTS   AGE
airflow-prometheus-exporter-559d667576-vn89w                                                           1/1     Running   0          21d
airflow-scheduler-58867cd7d8-2cb7k                                                                     1/1     Running   0          3d22h
airflow-web-cfdd75746-5mmt2                                                                            2/2     Running   0          3d22h
customerperformanceexportdataflowstockversionperformanceexportdaily-27bb19df62c545e0928f516be132f620   2/2     Running   0          15m
dataflow-stock-version-performance-export-daily-286630d7                                               2/2     Running   0          15m
transienttorawrawadverttextstockitemdatalaketransienttoraw-b1b58e6af8b045c3af25b067bcb956fd            2/2     Running   0          29m
transienttorawstockitemstrategyupdatedatalaketransienttoraw-a5cc8b7197fc492a9236c07ff18eeabc           2/2     Running   0          6h59m
transienttorawvehiclemetricsdatalaketransienttoraw-869326a9dee44d00bd74268cc9a0302c                    2/2    Running   0          29m
```

**Comment by rlenglet** [comment]
Instead of optionally enabling exposing the admin interface via TCP, how about optionally enabling exposing the UDS in an `emptyDir` volume? The UDS in that volume would be visible from any container in the pod.
That solves the problem of exposing this as a TCP service while still making the admin interface accessible from the rest of the pod (optionally).
@Stono would that work for you?

**Comment by Stono** [comment]
No it doesn’t as I really don’t have the engineering capacity right now to change everywhere we are doing this to use UDS instead.

I really don’t know why you can’t leave this tcp for those who want it?

**Comment by rlenglet** [comment]
> No it doesn’t, as I really don’t have the engineering capacity right now to change everywhere we are doing this to use UDS instead.
> I really don’t know why you can’t leave this tcp for those who want it and understand any associated risks?

Fine. I was exploring options.

**Comment by Stono** [comment]
Yeah you’d already mentioned uds earlier though so aren’t we going round in circles a bit?

Ultimately I’m just one user, so do what’s best for the product, not for me.

**Comment by duderino** [comment]
@abhide do you plan on doing this?  If not please let us know so we can find another owner

**Comment by duderino** [comment]
OK, I'm timing out on @abhide and finding a new owner.

Circling back on the result of a security related chat, the compromise we reached was: 1) continue listening on TCP loopback by default, 2) add an option to listen on UDS instead, 3) include advice to enable the UDS option in an upcoming 'how to harden your Istio cluster' doc (and sprinkle the same recommendation in the relevant existing docs).

@yxue can you pick this one up?  This has the urgency of an important feature request which means stability affecting bugs come first.  Thanks

**Comment by rlenglet** [comment]
I would suggest a slightly different plan:

- Always enable listening on UDS. There's no harm in doing that.
- Modify pilot-agent to always use that UDS.
- Add an option to also listen on TCP loopback.

**Comment by yxue** [comment]
We cannot listen on both TCP loopback and UDS. The protobuf definition of admin address is here

https://github.com/envoyproxy/envoy/blob/4300ad4544b500982d39fd0ddf83f38b40b80828/api/envoy/config/core/v3/address.proto#L121-L132

**Comment by rlenglet** [comment]
Argh. I hadn't checked whether `config.bootstrap.v2.Admin` could take more than one `config.bootstrap.v2.Admin` proto. Changing this would be quite invasive. 😞

**Comment by rlenglet** [comment]
OK, then the solution is to just use UDS in the bootstrap, and have pilot-agent optionally open a TCP port and forward connections to the Envoy UDS.

**Comment by yxue** [comment]
That sounds good to me. I am going to follow the plan:

1. continue listening on TCP loopback by default
2. add an option to listen on UDS, default to TCP loopback
3. switch default to UDS and have pilot-agent optionally open a TCP port
4. document how to disable listening on TCP to harden the cluster

**Comment by rshriram** [comment]
There are a plethora of debugging tools that are used to accessign the istio proxy admin endpoint on 15000. And most of our end users are also familiar with using the 15000 endpoint to get the dump via curl. If you change this to some UDS, then it creates a lot of pain for porting all the existing tools.

Secondly, I do not buy this `quit envoy and induce load on pilot` thing. There are several ways to induce load on pilot starting by simply hitting the Pilot service directly from Envoy. There is no end to DDOSing the system if we keep locking down all the debug endpoints, tools, etc. Also, the same malicious container or pod user could also mount the uds (as part of pod spec) and then overload envoy with it. I could overload enovy by simply calling Envoy on any port using 127.0.0.1:envoyPort (virtual inbound listener for example) so much that envoy crashes due to file descriptor scarcity or what not. That doesnt' mean we lock down or get rid of virtual inbound and everything else.

**Comment by yxue** [comment]
@rshriram  Instead of replacing the TCP loopback address with UDS, what do you think of adding UDS as an option and default to TCP loopback address? In this case, we can provide a security option for users who care about it without breaking existing users.

**Comment by rshriram** [comment]
Yes I dont mind if you want to create a UDS and enable it explicitly through annotation or what not. But TCP should always be the default. IMO it is unnecessary complexity, all in the name of a DDOS that is not even a legitimate threat. 

Here are a few more DDOS vectors to consider:
I could choose to launch a 1000 pods in one namespace and churn them in a specific way to bring pilot down to its knees. That doesn't mean we disable the ability to create 1000 pods in a namespace or just stop automatically processing XDS requests.

I can choose to create a Sidecar crd for each one of my 100+ pods in the namespace with some very eccentric imports/exports or large number of inbound/outbound listeners. Does this mean we stop using the Sidecar resource or stop allowing people to create more than 3 listeners in each sidecar or disallow workload specific sidecars completely?

I can do the same with authN policies and authZ policies, or any workload based API, with 100s of ports, or 100s of rules for each workload. Do we disable all of these security resources by default in the name of "security" and DDOS mitigation on Pilot?

My point is that DDOS is a very gray area. Load != DDOS. A pod is a load, and all lifecycle around the pod is the same to pilot. Whether the pod is legitimately in a crashloopbackoff state or someone is frequently doing `quit quit quit`, it is all the same. We have ways to dampen this at pilot. Singling out just the envoy level stuff and devising complicated workarounds is not sustainable solution esp when the solution causes inconvenience to all our users.

All said, a http proxy via pilot agent passing stuff to the UDS is an interesting idea that can help us property tie the lifecycle of the agent and envoy, as pilot agent can exit after envoy exits properly. This should pose no breakage to end user as long as we dont do unnecessary things like blocking out `/quit quit quit`.  That said, given that @Stono and others like him have already managed to control sidecar lifecycle using quit-quit-quit, I am assuming that the pilot agent terminates automatically if Envoy died properly with a 0 exit code [cc @howardjohn / @hzxuzhonghu - is this correct?]. If this is correct, then I see no point in investing time and effort towards the http proxy on pilot agent.

**Comment by howardjohn** [comment]
Pilot agent has its own quit endpoint, but in a later release we also made the agent exit when envoy exits so either one works

**Comment by costinm** [comment]
Since UDS is also in networking namespace - shared with the app - I'm not sure what the difference is in terms of security. If app can run as 1337 - and bypass envoy completely - it also doesn't matter much if it can access /admin - there is nothing /admin does that app bypassing envoy can't do. 

I think having a https + ACL interface to access admin and status from outside of the pod will be a better use of the time - replacing kubectl exec use in istioctl.

**Comment by rlenglet** [comment]
> Since UDS is also in networking namespace - shared with the app - I'm not sure what the difference is in terms of security.

I believe that's not true for unix domain sockets that are bound to the filesystem, which is what we're considering here.

**Comment by duderino** [comment]
@costinm think of it like a path traversal attack.  You can trick a web server's file serving mechanism to serve a different file.   In this case, you could trick a proxy into forwarding a request to a port accessible within the netns (the admin port).

But you can't trick the proxy into forwarding a request to a UDS socket because it doesn't have the code to do that.

**Comment by costinm** [comment]
I think you are forgetting we have an explicit API in Istio for supporting UDS-based servers. Forwarding to TCP or UDS is equally easy using Istio APIs :-) We discussed in the past 
the risk ( and benefits ) of exposing mysql UDS socket for example. 

We are generally trying to adopt "zero trust" - and use L6 authn and authz policies instead of 
relying on 127.0.0.1 or UDS. If the intent is to control who has access to the admin interface - we should use the same method we use for all our APIs, i.e. add a TLS filter and authz policy, and treat it  consistently with all other ports and services. 

In other words: I would go the opposite way, and have /admin exposed with mTLS and an
auth policy allowing spiffe://.../istio-system/istiod and few other SA to access it.

**Comment by duderino** [comment]
I think UDS forwarding requires explicit user enablement (vs. say something based on ORIGINAL_DST which could potentially be hijacked).   So unless a user specifically configured UDS forwarding to the admin port, could Envoy be tricked into forwarding there?   At this point it's more of an Envoy code question @PiotrSikora @jplevyak @lambdai @yxue 

Root question: does restricting the admin port to UDS make envoy any safer?

**Comment by htuch** [comment]
@duderino with zero knowledge on how Istio/k8s works, I can talk to the general case. Imagine you have an Envoy sidecar for a process in a VM. Even if binding to localhost, other local access to the VM can potentially access admin, which might constitute a privilege escalation, since admin is capable of mutating operations (e.g. quit, TAP) and data exfiltration (e.g. config dump). If you use appropriate network namespace controls this isn't an issue, but that is environment dependent. UDS can be locked down with regular file permissions.

**Comment by duderino** [comment]
@htuch can UDS be locked down such that the Envoy process can't be tricked into forwarding downstream requests to it?  I would imagine that the only way to prevent Envoy writing to the UDS would be to prevent everyone from writing to the UDS.

Or is it the case that Envoy just can't be tricked into forwarding downstream requests to it?  Or perhaps Envoy could only be tricked if certain routing rules were created (which my guess would be extremely rare)?

**Comment by htuch** [comment]
@duderino I don't see how it would forward to a UDS path unless that appeared explicitly in the CDS/EDS configuration somewhere. For TCP, I imagine dynamic forward proxy could do some interesting things. if enabled on a node (not an expert there though).

**Comment by eli-krem** [comment]
I might be missing something, but why was this issue closed? I don't see a solution for it.

**Comment by howardjohn** [comment]
Its closed as there is no work on this or plans to implement it, not because it was implemented (I think github is incorrectly calling it "completed")

**Comment by GabrielAlacchi** [comment]
@howardjohn a low hanging fruit way to achieve blocking access to port 15000 outright from application containers would be to leverage the `owner` module of iptables for filter table of OUTPUT chain of that pod's net namespace. We can either make it configurable to block specific UID / GID or just block non-root. The user of this feature would have to configure security context of their container to run as non-root for this to be effective, but at least there is a path to achieving sidecar/app container boundary that the OP was looking for here.

https://serverfault.com/questions/570668/how-to-block-access-to-a-local-user-to-a-local-port

I personally have an interest in this feature and would be willing to contribute if there's interest in accepting this approach.
