### ISSUE TITLE
Prepare 1.5 branches

### ISSUE THREAD

**Issue by fpesce** [istio/istio#20361]
This issue aims to track all steps needed to prepare the release 1.5 branches/builds.

Please add all steps taken here so we can document for future releases

- [ ] (Optional) Update go dependencies. This must be done **before branching** so that PRs can be easily backported later. (owner: @dgn ) _See discussion below if this should be a pre or post branch item._
  - [x] istio/istio #20420 
  - [x] istio/pkg istio/pkg#99
  - [ ] istio/api https://github.com/istio/api/pull/1242
  - [ ] ~~istio/cni https://github.com/istio/cni/pull/231~~ (@dgn: cannot be updated without code changes. will postpone until after branch is cut)
  - [x] ~~istio/operator~~
  - [x] ~~istio/installer~~
  - [x] istio/client-go https://github.com/istio/client-go/pull/39
- [x] Update common-files in _master_(owner: @fpesce). This will prevent larger differences between _master_ and the new release as the common-files are updated after the branching (only change should be branch).
  - [x] istio/istio https://github.com/istio/istio/pull/20394
  - [x] istio/pkg https://github.com/istio/pkg/pull/98
  - [x] istio/api https://github.com/istio/api/pull/1240
  - [x] istio/cni https://github.com/istio/cni/pull/230
  - [x] ~~istio/operator~~
  - [x] ~~istio/installer~~
  - [x] istio/client-go https://github.com/istio/client-go/pull/38
  - [x] istio/release-builder https://github.com/istio/release-builder/pull/117
  - [x] istio/gogo-genproto https://github.com/istio/gogo-genproto/pull/32
- [x] Set up release manager team (owner: @linsun ) - Make sure the new team has write access to the repositories.  istio/community#267
- [x] Adjust istio/proxy to correct version of istio/envoy https://github.com/istio/proxy/pull/2652
- [x] Create a `release-1.5` branch in every Istio repo - run commands `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout -b release-1.5 && git push --set-upstream origin release-1.5)`.
  - [x] istio/istio
  - [x] istio/pkg
  - [x] istio/api
  - [x] istio/cni
  - [x] istio/proxy  - Do not branch updated for Envoy 1.13 (owner: @PiotrSikora to notify @fpesce when this is done)
  - [x] istio/envoy - Do not branch updated for Envoy 1.13 (owner: @PiotrSikora to notify @fpesce when this is done)
  - [x] ~~istio/operator~~
  - [x] ~~istio/installer~~
  - [x] istio/client-go
  - [x] istio/tools
  - [x] istio/common-files
  - [x] istio/gogo-genproto
  - [x] istio/release-builder
  - [x] Explicitly skipped: istio-releases/pipeline, istio/tests, istio/istio.io, istio/test-infra
- [x] Set up prow on release branches (owner: @fpesce)
  - [x] istio/istio https://github.com/istio/test-infra/pull/2301
  - [x] istio/pkg https://github.com/istio/test-infra/pull/2301
  - [x] istio/api https://github.com/istio/test-infra/pull/2301
  - [x] istio/cni https://github.com/istio/test-infra/pull/2301
  - [x] istio/proxy https://github.com/istio/test-infra/pull/2301
  - [x] istio/envoy - does not use prow
  - [x] ~~istio/operator~~
  - [x] ~~istio/installer~~
  - [x] istio/client-go https://github.com/istio/test-infra/pull/2301
  - [x] istio/tools https://github.com/istio/test-infra/pull/2301
  - [x] istio/common-files https://github.com/istio/test-infra/pull/2301
  - [x] istio/release-builder https://github.com/istio/test-infra/pull/2301
  - [x] istio/gogo-genproto https://github.com/istio/test-infra/pull/2301
- [x] Set up branch protection (owner: @howardjohn ) istio/test-infra#2302 
- [x] Update all repos that point to master branch of another repo to point to the release branch. `master-latest-daily` -> `1.5-dev` (see https://discuss.istio.io/t/deprecation-notice-daily-builds/3991), `latest` -> `1.5-dev`, `git clone master` to `git clone release-1.4`, etc. Commit a PR into every `release-1.5` branch to modify every `CODEOWNERS` to contain only the release managers for this release. Command: `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout release-1.5 && git checkout -b release-1.5-codeowners && echo '* @istio/release-managers-1-5' > CODEOWNERS && git add CODEOWNERS && git commit -m 'Set release managers as CODEOWNERS for release-1.5' && git push --set-upstream origin release-1.5-codeowners)`.
  - [x] istio/istio https://github.com/istio/istio/pull/20559
  - [x] istio/pkg https://github.com/istio/pkg/pull/102
  - [x] istio/api https://github.com/istio/api/pull/1256
  - [x] istio/cni https://github.com/istio/cni/pull/233
  - [x] istio/proxy TODO after branch https://github.com/istio/proxy/pull/2641
  - [x] istio/envoy TODO after branch https://github.com/istio/envoy/pull/134
  - [x] ~~istio/operator~~
  - [x] ~~istio/installer~~
  - [x] istio/client-go https://github.com/istio/client-go/pull/42
  - [x] istio/tools https://github.com/istio/tools/pull/705
  - [x] istio/common-files https://github.com/istio/common-files/pull/184
  - [x] istio/gogo-genproto https://github.com/istio/gogo-genproto/pull/33
  - [x] istio/release-builder https://github.com/istio/release-builder/pull/122
  - [  ] istio/release-builder branch change in build.sh too! https://github.com/istio/release-builder/pull/144
- [x] Update common-files in _new release_. You first have to manually update the _common/Makefile.common.mk_ *update-common* target to point to the _new release_ and then run 'make update-common'. It may be that this step could be combined in the prior step in the 'make update-common' was done before the branch.
  - [x] istio/common-files should have the branch updated above.
  - [x] istio/istio
  - [x] istio/pkg https://github.com/istio/pkg/pull/105
  - [x] istio/api https://github.com/istio/api/pull/1264
  - [x] istio/cni https://github.com/istio/cni/pull/238
  - [x] ~~istio/operator~~
  - [x] ~~istio/installer~~
  - [x] istio/client-go https://github.com/istio/client-go/pull/46
  - [x] istio/gogo-genproto https://github.com/istio/gogo-genproto/pull/34
  - [x] istio/proxy
  - [x] istio/release-builder https://github.com/istio/release-builder/pull/124
- [x] Bump master to version 1.6 https://github.com/istio/istio/pull/20549
- [x] Stop publishing `latest` tags https://github.com/istio/istio/pull/20587
- [x] Run the long-running tests on the dev builds
- [x] Send announcement on Discuss/Slack/Twitter
- [x] Publish a beta release https://github.com/istio/release-builder/pull/128 / https://github.com/istio/release-builder/pull/127

**Comment by fpesce** [comment]
Checklist inspired from the 1.4 one:
c.f.: https://github.com/istio/istio/issues/17856

**Comment by PiotrSikora** [comment]
`istio/envoy` and `istio/proxy` are still blocked pending update to Envoy v1.13.0, which was released yesterday. Please don't branch them just yet.

**Comment by linsun** [comment]
@release-managers-1-5 have been created  cc @fpesce @johnma14 @dgn let me know if you have any issues.

**Comment by johnma14** [comment]
Thanks @linsun. Appreciate it.

**Comment by fpesce** [comment]
@PiotrSikora any ETA for Envoy branch cutting ?

**Comment by howardjohn** [comment]
Missing step: https://github.com/istio/test-infra/pull/2302 setting up prow branch protection

Also there is a "completed" item to add the release managers team. I am not sure why this is marked as completed as it has not been? This is done by https://github.com/istio/community/pull/267

**Comment by PiotrSikora** [comment]
The branching process is broken, and there is a mismatch across branches.

Notably, `istio/istio:release-1.5` points to `istio/proxy` that's 4 commits / 10 days older, and significantly different (see: unfinished #20519) than `istio/proxy:release-1.5`.

If we have explicit commit dependencies between projects, they need to be accounted for when branching, instead of simply branching from the `master` branch across all projects.

cc @fpesce @howardjohn @duderino

**Comment by howardjohn** [comment]
I believe the process is a WIP as it was started late Friday, what you described is on the check list

**Comment by fpesce** [comment]
> Also there is a "completed" item to add the release managers team. I am not sure why this is marked as completed as it has not been? This is done by [istio/community#267](https://github.com/istio/community/pull/267)

I think there was a small miscommunication following the comment https://github.com/istio/istio/issues/20361#issuecomment-576843786

**Comment by howardjohn** [comment]
> I think there was a small miscommunication following the comment 

I see, I was confused since I didn't see any activity in the org audit log, but I think my query was just wrong
