### ISSUE TITLE
Umbrella tracking issue for istioctl and multiple control planes

### ISSUE THREAD

**Issue by esnible** [istio/istio#21118]
This **will become** an umbrella issue for the work needed to make `istioctl` multiple control plane aware.  RFC (not yet approved): https://docs.google.com/document/d/1ecMIxUBgp5VDFqrBuu1ofyTHCwDKU1hWSLhewNKWIi4/edit

- [x] `istioctl manifest remove`/`uninstall` https://github.com/istio/istio/issues/18900 
- [x] `istioctl version` new parameters `--all` and `--icp-revision`
- [x] `istioctl wait`, `x authz`, `register`, `deregister`, `proxy-status`, `verify-install`, `x upgrade` all need `-icp-revision` flag
- [ ] `istioctl describe` should output the Istio Control Plane Revision that controls the pod
- [ ] `istioctl analyze` should look for namespaces labeled with non-existent ICP Revision.

**Comment by esnible** [comment]
I have put this on the 1.6 roadmap with a P0 or P1 priority.  Will work to get RFC approved and implement this.

The implementation should be attaching a `--control-plane` (or similarly named) flag to select which control plane revision when multiple control planes are present, and modifying istioctl's `PilotDiscoveryDo()` and `AllPilotDiscoveryDo()` to use that flag when finding Pilot/Istiod pods.

A few commands will need additional work, and produce additional output.

**Comment by esnible** [comment]
The over-all issue is https://github.com/istio/istio/issues/21934

**Comment by esnible** [comment]
Created https://github.com/istio/istio/issues/22274

**Comment by esnible** [comment]
Created https://github.com/istio/istio/issues/22749 for analyzer work.

**Comment by esnible** [comment]
@ostromart Need advice on "'istioctl analyze' should look for namespaces labeled with non-existent ICP Revision."

One strategy would be to expect an IOP CR for every control plane a cluster knows about (self-hosted, multi-cluster, or "central").  This would allow `analyze` and also the "admin list" command proposed in https://github.com/istio/istio/issues/23892 to work.  Currently the IOP is optional.  What do you think?

**Comment by esnible** [comment]
No stale

**Comment by esnible** [comment]
I'm pretty sure an Istio team member performed an activity 16 days ago, IstioBot!
