### ISSUE TITLE
Cleanup operator codebase

### ISSUE THREAD

**Issue by dgn** [istio/istio#21212]
This is an umbrella issue to discuss potential refactorings and improvements to the operator codebase.

**Comment by morvencao** [comment]
@dgn As you mentioned in the 1st item, we have gaps about the marshaler/unmarshaler between istioctl and in-cluster operator. Basically, for all the commands integrated with istioctl, we're using jsonpb unmarshaler, while for in-cluster controller, we need to retrieve and store the IOP instance from kube-apiserver with go-client lib, it's using the yaml/json unmarshalers by default. Besides, to merge default profile with IOP spec in controller, we also need jsonpb unmarshaler. 
AFAIK we need both of them, because currently the proto is the only source of truth for operator API.

**Comment by ostromart** [comment]
I'd like to add the following:
- [ ] Heavily prune back all the golden file outputs to retain only the resources relevant to the particular test.
- [ ] Take a hard look at the controller framework (pkg/controller & helmreconciler) and see if we still need it because it introduces a lot of code and makes the flow harder to follow.
- [ ] Take another stab at cleaning up the hacks we have in Go struct generation from proto.
- [ ] I'm pretty sure we still have several similar implementations of tree traversals floating around the codebase. Unify these with one syntax / capability set (under tpath?)
- [ ] get rid of most of pkg/manifest and use a common pkg to apply/prune objects (we already have such functionality in the controller, istioctl should use the same assuming it can be made performant enough)
- [ ] fswatcher never took off so it can likely be removed.
- [ ] general code tidiness and documentation. There are some parts left over after the pruning above that can use some cleanup and docs: quite a bit of the code under cmd/mesh and pkg/tpath.

**Comment by morvencao** [comment]
add item for in-cluster operator:
- [ ] add validating webhook for in-cluster operator so that we can validate the IOP instance before it is applied into apiserver.

**Comment by ostromart** [comment]
- [ ] remove initialisms all over the codebase e.g. https://github.com/istio/istio/pull/21412#discussion_r383492206

**Comment by richardwxn** [comment]
@morvencao actually I had a pending PR for that: https://github.com/istio/operator/pull/441 but we haven't justify the necessity for it so far based on our current validation need.

**Comment by dgn** [comment]
I added all items to the issue description, except the validation webhook. @morvencao I think that one is not necessarily cleanup-related and can go into a separate issue

**Comment by morvencao** [comment]
@dgn Correct.

**Comment by brian-avery** [comment]
How much of this is expected to be completed for 1.6?

**Comment by ostromart** [comment]
I think this is complete for 1.6. We've made some really important cleanups and I'm pretty happy with the state of the code to start the next release.

**Comment by howardjohn** [comment]
I think this can be considered as close to done as can be - all associated issues are closed.
