### ISSUE TITLE
Cleanup configuration of pilot-agent

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21222]
This tracks an effort to clean up the configuration of pilot agent. The root issue here is that we need to construct the meshconfig/proxy config in pilot-agent. To do this, we pass a variety of flags and environment variables to the agent, and reconstruct the config from these sources. This makes our injection templates and gateway deployments quite complicated and inconsistent.

The goal here is to make this fairly minimal - at best, we could have the deployment simply mount mesh config and run with no arguments and everything would work.

Action plan:

- [x] Add mesh config as an env var in the injection template, which is read by pilot agent: #20920. This allows us to remove extra fields like `--drainDuration="{{ formatDuration .ProxyConfig.DrainDuration }}"`, which is done in https://github.com/istio/istio/pull/21162.
- [x] Read labels and annotations from downward api, to remove helm hacks required to get these to agent: https://github.com/istio/istio/pull/21184
- [x] Allow annotations to override mesh config fields, to remove fields like `--discoveryAddress={{ annotation .ObjectMeta `sidecar.istio.io/discoveryAddress` .ProxyConfig.DiscoveryAddress }}` https://github.com/istio/istio/pull/21206
- [x] Make sure all of these are supported in Gateway as well. This will likely require the gateway to mount mesh config, since we cannot inject it as an environment variable. #21285
- [ ] Move fields that should be in mesh config to mesh config. This will allow us to remove fields like `--dnsRefreshRate={{ valueOrDefault .Values.global.proxy.dnsRefreshRate "300s" }}`.
- [ ] Remove all replaced env vars and flags in pilot-agent, only support reading from mesh config
- [ ] Consider doing the same for istio-init. This may be overkill though.
- [ ] Investigate all other usages of `.Values`. Can these be moved to mesh config? If so, move them and remove the need to pass values.yaml in the config map entirely
- [x] Remove deprecated fields from bootstrap config https://github.com/istio/istio/pull/21388
- [x] (maybe) Remove support for control plane bootstrap configuration, provided it is no longer needed for legacy mixer/galley https://github.com/istio/istio/issues/21222
- [ ] (maybe) move bootstrap template to yaml

**Comment by howardjohn** [comment]
Things to move to mesh config: 
* logLevel
* componentLogLevel (we can merge this into one field if we are ok with some post-processing, such that something like `info` is passed to envoy as -l but `http:info` as `componentLogLevel`)
* NO: cluster domain - I think this is the same trust domain
* statusPort
* stsPort

Things to remove:
* `--serviceCluster` can be determined in agent code from labels/pod name variables
* `--domain` can be determined from pod namespace env and trust domain from mesh config (todo verify this)
* dnsRefreshRate: https://github.com/istio/istio/pull/21283
* `--trust-domain` we already have it in mesh config...

**Comment by howardjohn** [comment]
This is 95% done. The rest is cosmetic mostly. Bumping to nebulous future P1
