### ISSUE TITLE
Use istiod to manage remote data planes

### ISSUE THREAD

**Issue by linsun** [istio/istio#22934]
**Describe the feature request**
We would like to enhance the shared control plane multicluster model to have istiod only running on main cluster.  The remote cluster should only have Istio configurations and webhook configurations and supply it is credential to main cluster to access remote cluster's kube API server.  The desire for such enhancement was presented to env and networking WG earlier in 1Q 2020.

The following WIs are included as part of this:
- [x] Enable Istiod to issue certificate to a remote cluster (https://github.com/istio/istio/issues/22918)
- [x] provide a lightweight istiod config chart for remote cluster #23548
- [x] ensure user can easily install mutating Webhooks configuration, istio sidecar inject cm and istio cm on the remote cluster.
- [x] configure mutating webhooks in remote cluster to use main cluster's sidecar injector (https://github.com/istio/istio/issues/23028)
- [x] provide custom host for istiod server certificate (#23239)
- [x] patch remote mutating WebHooks configuration with caBundle from central Istiod (#23561)
- [x] configure validation webhooks in remote cluster to use main cluster's istiod
- [x] configure remote cluster gateways and sidecars to use central cluster's discovery address, CA address. #23624
- [x] needs to create istio-ca-root-cert cm for each ns #23138
- [x] multicluster shared control plane broken: remote plane use remote plane's service local ip vs gateway ip. https://github.com/istio/istio/issues/23495
- [x] istioctl user-facing commands without kube-exec and port-forward https://github.com/istio/istio/issues/24114
- [ ] add automated tests for this scenario #23182
- [ ] documentation https://github.com/istio/istio.io/issues/7243
- [ ] central istiod: remote cluster 's Istio resources need to be propagated to sidecars #24430

<img width="689" alt="istiod-remote-cluster" src="https://user-images.githubusercontent.com/1588319/79236000-56578280-7e3a-11ea-86e9-c4b1c45082a3.png">

Design doc: https://docs.google.com/document/d/1r58al52otp1uvB7YFHh8ifA_78hYeyd0hNLq4qPDSUM/edit

**Additional context**

**Comment by linsun** [comment]
Initial steps are avail for folks who are interested in trying this out:

https://github.com/istio/istio.io/issues/7243. (One caveat, there is one issue we discovered very late in 1.6 release cycle that was just fixed today and it will be in 1.6.1.  Manual workaround is provided in 7243 when using 1.6 rcs.)

**Comment by serrien** [comment]
> Initial steps are avail for folks who are interested in trying this out:
> 
> [istio/istio.io#7243](https://github.com/istio/istio.io/issues/7243). (One caveat, there is one issue we discovered very late in 1.6 release cycle that was just fixed today and it will be in 1.6.1. Manual workaround is provided in 7243 when using 1.6 rcs.)

Hello,

I tried it with two cluster on EKS with Istio 1.6.5. I notice that create remote secret cmd must be execute before installing Istio on remote cluster othewise, ingress gateway on remote cluster dooesn't start.

Furthermore, I tried Cross-cluster routing in action : [https://istio.io/latest/docs/setup/install/multicluster/shared/#cross-cluster-load-balancing](url) but services endpoints are not created on the remote cluster :

```
kubectl get pod -n sample -l app=sleep --context=master -o name | cut -f2 -d'/' | \
    xargs -I{} istioctl -n sample --context=master proxy-config endpoints {} --cluster "outbound|5000||helloworld.sample.svc.cluster.local"
```

```
ENDPOINT               STATUS      OUTLIER CHECK     CLUSTER
10.96.145.243:5000     HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```

**Comment by linsun** [comment]
@serrien thanks for trying it.   For the service endpoints, you need to make sure your c1 and c2 has different network names and registry names (e.g. fromRegistry).  If you still have issue, would be good to open a separate issue as this WI is to track overall progress for it.  BTW, we have a central Istiod test now, would be good to compare what you have done different with our automated test:  https://github.com/istio/istio/pull/24373

**Comment by serrien** [comment]
@linsun thanks for your answer. c1 and c2 has different network names and registry names. I create the issue #25485 where i explain what i have done.

**Comment by esnible** [comment]
I marked "istioctl user-facing commands without kube-exec and port-forward #24114" done.

**Comment by esnible** [comment]
The only remaining issue is a docs issue, so removing the other areas.
