### ISSUE TITLE
perf dashboard and pipeline optimizations

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#22959]
This ticket is to track optimizations need to be done in perf dashboard:

- [ ] fix days trace back per user-session and file caching problems

- [x] secure the site, issue created here: https://github.com/istio/istio/issues/22406

- [ ] browser and mobile compatibility (this might be out of scope, I just listed it here in case some day we have time to work on it)

- [ ] monitoring and alerting (https://github.com/istio/istio/issues/23157)

- [ ] integrate with testgrid (https://github.com/istio/istio/issues/20015)

- [ ] add regression analysis and alerting (https://github.com/istio/istio/issues/24520)

- [x] add long-running test

- [x] fix data parsing, when there is no values, should append 0 not null.

- [x] associate benchmark run_id to a git_sha

- [x] flamegraph integration

- [ ] security issues, add authN and authZ.

- [ ] add tcp load test for perf benchmark (https://github.com/istio/istio/issues/27647)

- [ ] Add polyglot service scripts to load tests (https://github.com/istio/istio/issues/18951)

**Comment by carolynhu** [comment]
cc @clarketm
