### ISSUE TITLE
istioctl user-facing commands without kube-exec and port-forward (Central Istiod)

### ISSUE THREAD

**Issue by esnible** [istio/istio#24114]
To support Central Istiod, multicluster and/or VMs, _istioctl_ needs to work without the ability to KubeExec and PortForward into individual Istio control plane pods

The following WIs are included as part of this:
- [x] istioctl function review and validation for central istiod https://github.com/istio/istio/issues/23978
  - [ ] (dropped for 1.7) ~~identify precise Istiod for a pod in the mesh https://github.com/istio/istio/issues/22274~~
- [x] XDS Events (No issue, pull https://github.com/istio/istio/pull/23833)
  - (dropped for 1.7) "unsharded" view of XDS (https://github.com/istio/istio/issues/24703 ; may slip from 1.7) needed for non-flat network.
  - [x] If `--xds-addr <xds>`, istioctl use XDS *or* port-forward https://github.com/istio/istio/pull/25087
    - [x] Security for direct connection to `--xds-address`. https://github.com/istio/istio/issues/24905
      - [ ] (dropped for 1.7) ~~Mechanism to create certs or tokens for TLS connection https://github.com/istio/istio/issues/24008~~
  - (dropped for 1.7) ~~@costinm XDS Proxy in Agent (New issue https://github.com/istio/istio/issues/24394, pull https://github.com/istio/istio/pull/24398)  (May be unneeded because unsharding likely to slip.)~~
- [ ] (dropped for 1.7) ~~@therealmitchconnors `istioctl wait` https://github.com/istio/istio/issues/23891~~
- [x] @esnible `proxy-status [<pod>]` https://github.com/istio/istio/issues/23538
  - [x] @esnible ad-hoc /debug/syncz request, "almost CSDS" response https://github.com/istio/istio/issues/25373
  - [ ] ~~@therealmitchconnors XDS Event istio.io/nacks (https://github.com/istio/istio/issues/24705 , design at https://docs.google.com/document/d/1X7DmkP10x4nEcTGpikxmvLbBTTK59B0WL3liQzVy8Ms/edit )~~
- [x] @esnible `version` https://github.com/istio/istio/issues/24331 

![image](https://user-images.githubusercontent.com/3237651/86160599-fc319980-bad9-11ea-83ce-54ff0429e6d4.png)

- If no --xds-addr <addr> , use k8s to list istiods and port-forward to them.  XDS event query for each.
- Else contact XDS, Pilot itself finds it's peers using ClusterLoadAssignment of istiod|15012.

(_istioctl_ can't do ClusterLoadAssignment and talk directly to IPs because they will be private IPs not exposed via cluster 1's ingress GW)

**Comment by esnible** [comment]
Everything for 1.7 has been completed or retargeted for 1.8.  Closing.
