### ISSUE TITLE
multi-network causes extra gateway hops

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#26293]
** Tasks **
- [X] Make EDS use REQUESTED_NETWORK_VIEW (#26729) 
- [x] Add samples/test for a separate east-west gateway, with network view set (#27222)
- [x] Include east-west gateway in multicluster/multinetwork docs
- [x] Add support to istioctl for more easily deploying east-west gateway

**Bug description**

<details>

<summary> Bug description </summary>

In https://github.com/istio/istio/pull/26393, it's apparent that when load balancing traffic for the same service deployed in different networks, the instances in the same network as the origin are preferred. 

Note: In the example below, clusters 0, 1 and 2 share a network, clusters 3 and 4 share a different network. Every cluster has an ingress-gateway. 

```
2020-08-12T22:19:37.531901Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-0]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:26 cluster-1:30 cluster-2:32 cluster-3:4 cluster-4:8]
2020-08-12T22:19:37.940415Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-0] (408.506665ms)' ===
=== RUN   TestCrossClusterLoadbalancing/loadbalancing/from_cluster-1
2020-08-12T22:19:37.940744Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-1]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:28 cluster-1:20 cluster-2:25 cluster-3:12 cluster-4:15]
2020-08-12T22:19:38.325885Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-1] (385.133412ms)' ===
=== RUN   TestCrossClusterLoadbalancing/loadbalancing/from_cluster-2
2020-08-12T22:19:38.326141Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-2]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:24 cluster-1:28 cluster-2:25 cluster-3:15 cluster-4:8]
2020-08-12T22:19:38.770892Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-2] (444.742841ms)' ===
=== RUN   TestCrossClusterLoadbalancing/loadbalancing/from_cluster-3
2020-08-12T22:19:38.771178Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-3]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:20 cluster-1:14 cluster-2:14 cluster-3:23 cluster-4:29]
2020-08-12T22:19:39.162013Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-3] (390.829998ms)' ===
=== RUN   TestCrossClusterLoadbalancing/loadbalancing/from_cluster-4
2020-08-12T22:19:39.162233Z	info	tf	=== BEGIN: Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-4]' ===
    loadbalancing.go:64: requests were not equally distributed among clusters: map[cluster-0:17 cluster-1:15 cluster-2:18 cluster-3:27 cluster-4:23]
2020-08-12T22:19:39.566030Z	info	tf	=== DONE (failed):  Test: 'multicluster_base[TestCrossClusterLoadbalancing/loadbalancing/from_cluster-4] (403.791484ms)' ===
```

This is likely due to the fact that the gateways in each network/cluster perform their own client side loadbalancing to the destination service. The gateways in the second network may include the gateways from the first network in their endpoints adding more complexity.

Given a setup with:
- 3 clusters in network 1
- 2 clusters in network 2
- the same "echo" service in every cluster
- an ingress gateway in every cluster

An envoy in network1 will have 3 endpoints for the local network's instances, and 2 endpoints for each of the remote gateways. The logic in  [EndpointsByNetworkFilter](https://github.com/istio/istio/blob/4d59ea4d42d69d2323d25e66eec5180ec0ef7b80/pilot/pkg/xds/ep_filters.go#L33) ensures that network1 endpoints will have a weight of 2 while the network2 gateway endpoints will also have a weight of 2. 

IIUC the gateways themselves will also perform some load-balancing that may further skew this. Routing requests back to the origin cluster. I need to confirm/deny this with somehow. 

https://github.com/istio/istio/blob/4d59ea4d42d69d2323d25e66eec5180ec0ef7b80/pilot/pkg/xds/ep_filters.go#L28-L41

**Expected behavior**

Traffic is nearly even to each cluster in the mesh.

**Steps to reproduce the bug**

1. Setup a mesh with at least 2 clusters in one network and 1 cluster in another. 
2. Deploy the same service to all clusters. 
3. From the network with multiple clusters, make a large number of requests. 
4. Check the origin of the responses. This bug causes them to mostly come from clusters in the origin network. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Latest master (1.7.x)

**How was Istio installed?**

Using the test framework

**Environment where bug was observed (cloud vendor, OS, etc)**

KinD, GKE. 

</details>

**Comment by stevenctl** [comment]
Looks like this applies for all cross-network traffic. Only one cluster on the foreign network seems to get hit.

**Comment by stevenctl** [comment]
cc @hzxuzhonghu - can you help me understand how the weighting of local endpoints normalizes things? Can it interfere with weights set by other istio config?

**Comment by hzxuzhonghu** [comment]
To better understand the weight calc,  it's better to look at the ut.  It treats each endpoint as weight 1, and definitely it is not right if we set workloadentry with a weight, let's say 10. And there is another endpoint(pod) in another network, we have no way to set weight, so it's weight is 1.  In this case, the weight of WLE will not be respected.

**Comment by tbarrella** [comment]
(here is a [logs dump](https://gcsweb.istio.io/gcs/istio-prow/pr-logs/pull/istio_istio/26586/integ-multicluster-k8s-tests_istio/9026/artifacts/multicluster-base-07b0c0a757cd4/TestCrossClusterLoadbalancing/loadbalancing/) from running tests on #26586)

**Comment by stevenctl** [comment]
Per @tbarrella 

> https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/26698/integ-multicluster-k8s-tests_istio/9224/artifacts/multicluster-base-2d2f4d976ebe4/TestCrossClusterLoadbalancing/_test_context/mc-reachability-1-89669-state133681783/echolb-v1-6b6d5846f6-nklc5-istio-proxy.log
which is for echolb in cluster-1, where most of the requests are from 172.18.0.4 (somewhere in cluster-0, expected), but a few are from 172.18.0.2 (somewhere in cluster-2) and also 10.20.0.8 (gateway-1)
ok yeah, looks like there definitely is stuff like
cluster-0 -> X -> gateway for cluster-1 -> echolb in cluster-1

It seems like one issue is the gateway then forwarding traffic to other gateways. Maybe for gateways we don't give them the endpoints for other gateways here:

https://github.com/istio/istio/blob/master/pilot/pkg/xds/ep_filters.go#L33

**Comment by stevenctl** [comment]
Re-purposing this issue for the ping-ponging problem. Going to investigate if all ingress (with replicas) messes with traffic shifting/distribution.

**Comment by stevenctl** [comment]
Reopening this - the solution is only in our tests and not in any code/docs.

**Comment by hzxuzhonghu** [comment]
What do you mean by this?

**Comment by stevenctl** [comment]
Making EDS respect requested network view is one part, but we don't document it or give sample deployments that use it for multi-network.

**Comment by hzxuzhonghu** [comment]
Thanks,  this is necessary.
