### ISSUE TITLE
Istio tooling is familiar and helpful to users

### ISSUE THREAD

**Issue by esnible** [istio/istio#26855]
From Roadmap: https://docs.google.com/document/d/15J59Bz4ogsM5my1dtEycgPq8uOPB93uy8CU5-Ehv2qw/edit#

- [x] P2 https://github.com/istio/istio/issues/26080 istioctl accept kubectl syntax `[<type>/]<name>` [esnible]
- ~~[ ] P>2 https://github.com/istio/istio/issues/26267 Command to enable/disable injection for namespace~~
- Analyze improvements
   - [ ] P2 https://github.com/istio/istio/issues/22872 Line numbers (already a PR!) [jasonwzm]
   - [x] P2 https://github.com/istio/istio/issues/25533 troubleshooting Virtual Service match duplicate analyzer [esnible]
   - [ ] P1 https://github.com/istio/istio/issues/26220 Align pre-check and verify-install messages with analyze [jason wang]
- [ ] P1 https://github.com/istio/istio/issues/22274 Make `--revision` unneeded in CLI -- find control plane from pod [esnible]
- [ ] P1 https://github.com/istio/istio/issues/23892 new istioctl command to list control planes “available” for a single K8s cluster [esnible]
  - [x] istioctl x list injectors [merged to master, not 1.8 branch]
  - [ ] istioctl x istiod list [PR https://github.com/istio/istio/pull/27737]
- [ ] P1 https://github.com/istio/istio/issues/23891 istioctl wait needs to support a way to wait for all/some control planes, even with Central Istiod [mitch]
- [ ] P1 https://github.com/istio/istio/issues/24920 Envoy Extension Dashboard **needs owner, perhaps co-owned by someone from UX and Telemetry working group**
