### ISSUE TITLE
[1.8] Ecosystem developers can integrate troubleshooting features

### ISSUE THREAD

**Issue by esnible** [istio/istio#26858]
UX Affecting Istio 3rd party ecosystem
Ecosystem developers can integrate troubleshooting features

- [ ] P1? Troubleshooting API (slipped in 1.7)
- [ ] P0 #23536 Need approved document.  Owner [esnible, mitch, liam]
  - For 1.8, make Go /pkg to be ready for it.
     - Move as much as possible into single debug API
     - Blocker for debug/wait on Central Istiod
- [ ] P1 #23537 Experimental/MVP in Istiod [mitch]
- [ ] P1 #24795 Distribution status [mitch]

This item taken from [Roadmap](https://docs.google.com/document/d/15J59Bz4ogsM5my1dtEycgPq8uOPB93uy8CU5-Ehv2qw/edit#)
