### ISSUE TITLE
UX Affecting Istio cloud operators / admins

### ISSUE THREAD

**Issue by esnible** [istio/istio#26857]
UX Affecting Istio cloud operators / admins 

- Admin can promote canary control planes to master with a single command [mitch]
  - [ ] P1? #23889 Rewrite injector ConfigMaps to select control plane "master" (with environments; slipped from 1.7) **Needs RFC, needs that RFC approved by Environments, needs implementor.  Any volunteers?**
- Admin can evaluate control plane health with single command
  - [ ] P1 #21715 Real control plane health check (also needed by end users) [esnible]
     - Sync with John Howard
- Admin can non-destructively upgrade control planes
  - [ ] P2 #23443 upgrade inheriting current cluster settings **needs owner**
- Admin can use istioctl to control log level
  - [x] P2 #24922 Set control plane log level

This item taken from [Roadmap](https://docs.google.com/document/d/15J59Bz4ogsM5my1dtEycgPq8uOPB93uy8CU5-Ehv2qw/edit#)

**Comment by piotrkpc** [comment]
The last item recently landed into master - https://github.com/istio/istio/pull/25276
