### ISSUE TITLE
istioctl verify-install related issues

### ISSUE THREAD

**Issue by shamsher31** [istio/istio#28148]
This issue is to track `istioctl verify-install` related problems.

`verify-install` still fails on the master.
```
$ ./out/linux_amd64/istioctl verify-install
Error: could not load IstioOperator from cluster:
could not unmarshal: json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```
- [x] https://github.com/istio/istio/issues/26266 : reports 'Checked 0 custom resource definitions'
- [x] https://github.com/istio/istio/issues/25830 : fails on parsing error on istio in 1.6.0
- [x] https://github.com/istio/istio/issues/26070 : doesn't work with dev builds
- [x] https://github.com/istio/istio/issues/25688 : fails on Kubernetes 1.18 fixed on Master by https://github.com/istio/istio/pull/28255 , still a problem on 1.8.x
- [x] https://github.com/istio/istio/issues/26265 : Integration test for 'istioctl verify-install'
- ~~[ ] https://github.com/istio/istio/issues/25848 : nil pointer error with `istioctl verify-install` on v1.6.x~~
- [x] https://github.com/istio/istio/issues/18855 : Enhance istioctl verify-install output
- [x] https://github.com/istio/istio/issues/26276 : Asset charts/addons/grafana not found
- [x] https://github.com/istio/istio/issues/28536 : does not work
- [x] https://github.com/istio/istio/issues/29336 : should colorize output
- [x] https://github.com/istio/istio/issues/29371 : output for canaried control plane and Istio Operator controller.
- [ ] https://github.com/istio/istio/issues/29413 : should it wait for rollout?
- [x] https://github.com/istio/istio/issues/29440 : does not work if the Istio is installed with --revision flag 
- [x] **new** https://github.com/istio/istio/issues/29607 : confusing message against external istiod data plane

**Comment by shamsher31** [comment]
@esnible Looks like we have covered and closed all the issues except https://github.com/istio/istio/issues/29413 one.

**Comment by ldemailly** [comment]
I get

istio-1.8.3/bin/istioctl verify-install

Error: could not load IstioOperator from cluster: control plane revision "" not found.  Use --filename

after an otherwise successful install of
istio-1.8.3/manifests/charts/base
istio-1.8.3/manifests/charts/istio-control/istio-discovery
istio-1.8.3/manifests/charts/gateways/istio-ingress

**Comment by shamsher31** [comment]
> istio-1.8.3/bin/istioctl verify-install
> 
> Error: could not load IstioOperator from cluster: control plane revision "" not found. Use --filename

@ldemailly thanks for reporting. I think it is fixed by https://github.com/istio/istio/pull/29442. I will cherry-pick it so it will be available in `1.8.4`.

**Comment by esnible** [comment]
There is only one item left.  There is no point on having a tracking issue for one item.  Closing in favor of https://github.com/istio/istio/issues/29413

**Comment by wnz27** [comment]
![istio-install1](https://user-images.githubusercontent.com/12094918/153129473-6acdf754-033c-4be9-b56b-f4a979e5872a.png)
![istio-install2](https://user-images.githubusercontent.com/12094918/153129480-3e2ba0a4-709a-41e3-a8e3-2915ad242694.png)
i'cant understand these problem

**Comment by wnz27** [comment]
> ![istio-install1](https://user-images.githubusercontent.com/12094918/153129473-6acdf754-033c-4be9-b56b-f4a979e5872a.png)
> ![istio-install2](https://user-images.githubusercontent.com/12094918/153129480-3e2ba0a4-709a-41e3-a8e3-2915ad242694.png)
> i'cant understand these problem

demo.yaml:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi

    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        service:
          ports:
            ## You can add custom gateway ports in user values overrides, but it must include those ports since helm replaces.
            # Note that AWS ELB will by default perform health checks on the first port
            # on this list. Setting this to the health check port will ensure that health
            # checks always work. https://github.com/istio/istio/issues/12503
            - port: 15021
              targetPort: 15021
              name: status-port
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
            - port: 31400
              targetPort: 31400
              name: tcp
              # This is the port where sni routing happens
            - port: 15443
              targetPort: 15443
              name: tls

    pilot:
      k8s:
        env:
          - name: PILOT_TRACE_SAMPLING
            value: "100"
        resources:
          requests:
            cpu: 100m
            memory: 150Mi

  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi

    pilot:
      autoscaleEnabled: false

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false

```
