### ISSUE TITLE
UX WG 1.9 roadmap

### ISSUE THREAD

**Issue by esnible** [istio/istio#29158]
**This is not yet approved, but this is what we will propose to the TOC**

- Upgrade
  - [ ] [is it possible? (w/Environments)](https://github.com/istio/istio/issues/28915) @sdake
  - [ ] [includes risk (Alpha, Experimental features)?](https://github.com/istio/istio/issues/29154) **NEEDS OWNER**
  - [ ] [Requires remediation (using deprecated APIs, old K8s version, etc)](https://github.com/istio/istio/issues/29156) **NEEDS OWNER**
  - [ ] [Am I using custom/non-vanilla settings?](https://github.com/istio/istio/issues/23892) @esnible 
  - [ ] [Did it succeed?](https://github.com/istio/istio/issues/28148) @esnible 
- Multiple control planes
  - [ ] See which dataplanes are connected where (also #23892 ) @esnible 
  - [ ] Safely remove old control plane once unused **TDB, with Environments**
- [ ] [Promote CRD status to beta](https://github.com/istio/istio/issues/29157) @therealmitchconnors 
- [ ] [Promote or remove istioctl CLI features](https://github.com/istio/istio/issues/29153) @esnible and @carolynhu 
- [ ] [Machine-readable API for istioctl commands](https://github.com/istio/istio/issues/26858) @therealmitchconnors and @esnible
