### ISSUE TITLE
Issues related to external/remote control plane

### ISSUE THREAD

**Issue by esnible** [istio/istio#29803]
This is a tracking issue.  (Feel free to re-order or prioritize these)

cc @linsun 

- [ ] `istioctl verify-install` https://github.com/istio/istio/issues/29607
- [ ] pod injector invalid when CNI settings different between external and remote plane https://github.com/istio/istio/issues/29618
- [ ] allow different cluster to use different image hub https://github.com/istio/istio/issues/29772
- [ ] Automated test for upgrading from incluster istiod to external istiod https://github.com/istio/istio/issues/29304
- [ ] External Control Plane: MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found https://github.com/istio/istio/issues/29659
- [ ] simplify external istiod and MC config for remote cluster https://github.com/istio/istio/issues/28708
- [ ] track external Istiod promotion WIs to beta https://github.com/istio/istio/issues/27669
- [ ] External istiod beta graduation https://github.com/istio/istio/issues/27136
- [ ] Integration testing for external istiod https://github.com/istio/istio/issues/27134

The following items aren't strictly related to external istiod, but adjacent:

- [ ] istioctl ps or pc adds debugging function for virtual machine scenarios #29052
- [ ] the istioctl debug tool in Primary-Remote model behavior improperly #29900

**Comment by linsun** [comment]
@esnible thanks for opening this - great to have all issues in one place.

Note: #27669 tracks issues specifically needed for beta graduation.  We can use this to track other issues.
