### ISSUE TITLE
Issues related to CR status

### ISSUE THREAD

**Issue by esnible** [istio/istio#30179]
**Commit to analyzer stuff for 1.10.  De-emphasize distribution status**

Tracking issue.  Please set Github priorities and milestones for these.

- [ ] #31122 analysis: panic in reporter removeCompletedResource
- [ ] #27330 Istiod restart seems to break `istioctl wait`
- [ ] #29709 panic in pilot: GetAdapter (when Istio installed with enableAnalysis: true)
- [ ] #30514 analysis mixes camel and snake case
- [ ] #30513 analysis missing message
- [ ] #30512 analysis level formatted wrong 
- [ ] #30511 distribution: "X/Y proxies up to date" api is not feasible
- [ ] #30498 distribution: NACKs treated as reconciled 
- [ ] #30362 Pilot log complaint when deleting EnvoyFilter with enableAnalysis=true
- [ ] #30292 crash
- [ ] #30284 status: resources stuck in "not reconciled" 
- [ ]  #30200 status: wasteful re-runs of analyzers leaders to large allocations
- [ ] #30218 excessive CPU on proxy events
- [ ] #30164 Excessive API server watches **P2**
- [x] #30160 "panic: session.stop: Invalid state: terminating" **P1** PR Pending
- [x] #30133 panic in CRD discovery **P1** PR Pending
- [ ] #30130 CRD updates lead to excessive logs (and, possibly, perf impacts) **P2**
- [x] #30128 strip spec on UpdateStatus **P2** CLOSED
- [ ] #30127 reconciled unexpectedly goes from True -> False **P1** PR Pending
- [ ] #30126 excessive goroutines/work done cluster without activity **P2** Cannot reproduce
- [x] #30123 inefficient marshalling **P2** PR Pending
- [ ] #30120 Status API issues
- [ ] #30122 status updates not resilient to conflicts during writes **P2**
- [ ] #29315 TestWait flake **P2**
- [ ] #29157 promote "CRD status" feature to beta - Tracking Issue
- [x] #28797 istiod memory extremely high when status enabled
- [x] #28687 Does ledger memory leak?
- [ ] #28015 StatusReporter memory leak **P2**
- [x] #27978 Frequent pilot crashes in CI after enabling analysis by default
- [ ] #27953 Move pilot analysis test **P2**
- [x] #27091 Pilot status reporter spawns unbounded number of goroutines for updates; eventually causing OOM
- [x] #25091 Don't do ledger put on updatesame
- [ ] #23160 Add observability to ledger **P2**
- [x] #22478 Galley panic on analysis **P1** PR Pending
- [x] https://github.com/istio/istio.io/issues/8797 Doc test for [this page](https://istio.io/latest/docs/ops/configuration/mesh/config-resource-ready/) @esnible 
- [x] https://github.com/istio/istio.io/issues/8805 Typo in documentation @esnible

cc @howardjohn

**Comment by howardjohn** [comment]
@therealmitchconnors I had some different opinions on some. I classified them as blocker/non blocker for beta:

- #30164 Excessive API server watches - **blocker for default, beta is borderline**
- #30160 "panic: session.stop: Invalid state: terminating" - **blocker, cannot panic**
- #30133 panic in CRD discovery - **blocker, cannot panic**
- #30130 CRD updates lead to excessive logs (and, possibly, perf impacts) - **not a blocker, but would REALLY like it to be fixed. No one likes log spam**
- #30127 reconciled unexpectedly goes from True -> False **- blocker; its a fundamental flaw**
- #30126 excessive goroutines/work done cluster without activity - **blocker, perf here is a huge issue**
- #30123 inefficient marshalling - **Doesn't matter if perf is reasonable through other means**
- #30122 status updates not resilient to conflicts during writes - **not a blocker IF we determine it doesn't impact correctness - but I think it does**
- #29315 TestWait flake - **Not a blocker**
- #28015 StatusReporter memory leak  - **needs investigation**
- #27953 Move pilot analysis test - **not a blocker**
- #23160 Add observability to ledger  - **not a blocker**
- #22478 Galley panic on analysis P1 - **blocker**


All of the ones that crash are clearly blockers, in my opinion

**Comment by mandarjog** [comment]
Distribution and analysis are 2 features that are going in together, per previous understanding.
The panics are all in the Galley side of the code base that is involved in the "analysis" feature. 

Next steps
1. Mitch will provide a detail plan on how "status" only graduation is possible. All stability related blockers above must be fixed.
2. We agreed (howardjohn & therealmitchconnors) that extra watches are not ideal, but should not block graduation.
3.  Do a time boxed effort on finding root cause of panics.

**Comment by therealmitchconnors** [comment]
Per conversation with @mandarjog and @howardjohn, the P1's listed above are considered blockers to release, and I am working on them now.  Specifically, the following are the remaining release blocking bugs:
#30160, #30128, #30133, #22478

**Comment by costinm** [comment]
I think the API review and approval by TOC - in particular around the controversial status fields - is still required ?

**Comment by howardjohn** [comment]
Added https://github.com/istio/istio/issues/30736, definitely a blocker

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/33095

not stale

**Comment by howardjohn** [comment]
Only one task left, and half of the feature was removed recently.. time to close this I think
