### ISSUE TITLE
Analyzers tracking issue

### ISSUE THREAD

**Issue by esnible** [istio/istio#30266]
This issue tracks analyzers under consideration, as well as analyzers we desire

**Analyzers to implement**

- [ ] Duplicate HTTPS virtual services leads to "multiple filter chains with the same matching rules are defined" #30321
- [ ] ServiceEntry with TCP protocol will override other settings #29992 @esnible 1.10
- [x] conflicting ports #29302
- [ ] analyzers for experimental and alpha features #29154 @esnible 1.10
- [ ] Refactor Multicluster Analyzer #28906 @jasonwzm 1.10
- [x] Add analyzer for incompatible host between VS and GW #28172 @zufardhiyaulhaq 
- [x] ServiceEntry without protocol for https port removes PassthroughCluster routing #27990
- [x] protocol conflicts on Gateway transparently droppped #27481
- [ ] Incorrect 'istioctl analyze' when multiple control planes inject different sidecar images #27392 @jasonwzm 
- [ ] VirtualService and Gateway mismatch has no validation #27070 **needs owner**

**Analyzers that seem wrong, but need consensus to fix**

- [ ] Extra istioctl analyze messages [IST-0136] desired? #30405
- [ ] Sample samples/multicluster/expose-istiod-https.yaml fails istioctl analyze #28510
- [ ] GatewayPortNotOnWorkload analyzer logic seems to be incorrect #28259
- [x] "istioctl analyze" doesn't like the 1.9 EnvoyFilters #30265
- [ ] "istioctl analyze" and analysis framework support exportTo #24572
- [ ] Analyzer should detect port and host conflict within gateway resources #23235

**Analyzers to consider**

- [ ] precheck analyzer #28915 (was @sdake )
- [ ] Improve analyze for duplicate VirtualService matches #27130
- [ ] Deprecation warnings or (patch type warnings) for EnvoyFilter patches #24743
- [ ] istioctl analyze error on overlapping matches #24707

**Issues for 'analyze' itself**

- [ ] istioctl analyze: dedupe outputs #28511 **needs owner**
- [ ] istioctl analyze errors with IST0101 when VS is referencing k8s service without SE #26222 **needs owner**
- [ ] Move Analysis Framework to Istiod #23943

** Issues for Istiod and the `Status` field**

- [ ] Enable more analyzers in Istiod #25917 **needs owner**

**Comment by esnible** [comment]
not stale
