### ISSUE TITLE
Delta xDS tracking

### ISSUE THREAD

**Issue by adiprerepa** [istio/istio#31638]
An issue to track the progress of delta xDS within istio.

[Design doc](https://docs.google.com/document/d/1hwC81_jS8qARBDcDE6VTxx6fA31In96xAZWqfwnKhpQ/edit#)

cc @howardjohn 

- [x] Initial implementation (https://github.com/istio/istio/pull/31212)
- [x] start with deltas for CDS (least CRDS impact) (https://github.com/istio/istio/pull/34029)
- [x] integration tests
- [ ] enable by default
- [ ] Possibly explore on-demand?
- [x] Get current integration tests to work when delta is enabled (https://github.com/istio/istio/pull/31832)
- [x] https://github.com/istio/istio/issues/32565

**Comment by howardjohn** [comment]
I would add "get all existing integration tests to pass when enabled". That is probably the most important, as it shows that we have feature parity with SotW

**Comment by adiprerepa** [comment]
Not stale

**Comment by linsun** [comment]
reopen

**Comment by howardjohn** [comment]
Delta xDS is on by default in 1.22 :partying_face:
