### ISSUE TITLE
Design Istio service config

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#3456]
Istio config model v1 is the same as today. See https://docs.google.com/document/d/1PNzYnG0pl5Bubtx-rGwHFWDnBRkrT9upw5mhMA8EpM8/edit

Config model v2 is the new configuration flow with Config architecture: https://goo.gl/Jft4jf

- [ ] Design service representation

- [ ] Design service config

- [ ] Design consumer config

**Comment by cmluciano** [comment]
cc @cmluciano

**Comment by ozevren** [comment]
This is not actionable at this point. Closing.
