### ISSUE TITLE
Istio API governance

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#3457]
- [x] API documentation: [link](https://groups.google.com/d/msgid/istio-dev/CALuuQPDVystyRgrwUm3qdtsMudS6gNTrG43EMxcY0U2ys-b%2Bmg%40mail.gmail.com?utm_medium=email&utm_source=footer)
- [x] API style guide: https://github.com/istio/api/pull/343
- [ ] proto package update
- [ ] API linter.
- [ ] [Add proto validator into istio/api and istio/istio](https://github.com/istio/istio/issues/3110)

**Comment by xiaolanz** [comment]
https://github.com/istio/api/pull/343
