### ISSUE TITLE
Istio UX 1.12 roadmap

### ISSUE THREAD

**Issue by esnible** [istio/istio#34682]
From [Approved Doc](https://docs.google.com/document/d/1DzYwC0F_sYWSSYz2gkFs8F2cqfH--whDPuWd-vf7_jQ/edit#)

- [ ] P0 - Feature Maturity - APIs, Labels, etc. - Iris, Steve
   - https://github.com/istio/api/pull/2013 API Repo
- [ ] P0 - Suppress Alpha Maturity on Default Options - Mitch Connors
   - @therealmitchconnors Can you create an issue for this, or link to the existing one?
- [ ] P0 - Support Stable API Promotion - Justin Pettit
   - @justinpettit Can you link to the Issue or create one
- [ ] P1 - Analyzers in Status (and refactor, carried from 1.9) - Jason Wang
  - [ ] #29154
- [ ] P1 - External Control Plane Troubleshooting - EdSnible@gmail.com
   - Carried over from 1.8, substantial progress made in 1.10
   - [ ] #22274
   - [ ] #34683
- [ ] P2 - Design Opt-In Usage Data Collection - Mitch Connors
   - @therealmitchconnors Can you create an issue for this, or link to the existing one?
- [ ] P2 - Support Beta APIs in istioctl - UNOWNED, and maybe should be higher than P2
   - [x] #28719

**Comment by ericvn** [comment]
I did update the Issues pointed to here with:

1.  the 1.12 milestone,
2. the new roadmap/1.12 label,
3. and their project priorities to match above
