### ISSUE TITLE
Evaluation of features

### ISSUE THREAD

**Issue by johnma14** [istio/istio#34806]
Revisit and evaluate the status of features in Istio based on the requirements for alpha, beta and stable.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by johnma14** [comment]
The purpose of this  feature is to track all the [existing features in Istio](https://istio.io/latest/docs/releases/feature-stages/) and:

1.  Make sure all existing features have a feature status page in the [enhancements repo](https://github.com/istio/enhancements)
2. Every feature status page reflects the correct status (experimental/alpha/beta/stable) of the feature and correct owners.
3. As we graduate these features, this feature status page will be used to track them (go through the checkboxes for the appropriate status. Currently, for new features we have owners creating new feature status page for these new features coming in.)

Currently we have 22 PR's that are still open in the enhancement repo for [this feature](https://github.com/istio/enhancements/pulls/johnma14). I have grouped them according to WG's to make it easier for reviewers/WG leads to go over:

### **_List of PR’s that need reviews from feature owners/WG leads :_**

**Traffic Management**

- [ ] [Traffic Control: label/content based routing, traffic shifting](https://github.com/istio/enhancements/pull/58)
- [ ] [TLS termination and SNI Support in Gateways](https://github.com/istio/enhancements/pull/61)
- [ ] [SNI (multiple certs) at ingress](https://github.com/istio/enhancements/pull/62)
- [ ] [Enabling custom filters in Envoy](https://github.com/istio/enhancements/pull/63)

**Observability**

- [ ] [Prometheus Integration](https://github.com/istio/enhancements/pull/47)
- [ ] [Service Dashboard in Grafana](https://github.com/istio/enhancements/pull/48)
- [ ] [Distributed Tracing](https://github.com/istio/enhancements/pull/50)
- [ ] [Stackdriver Integration](https://github.com/istio/enhancements/pull/53)
- [ ] [Distributed Tracing to Zipkin/Jaeger](https://github.com/istio/enhancements/pull/80)
- [ ] [Trace Sampling](https://github.com/istio/enhancements/pull/81)
- [ ] [Request Classification](https://github.com/istio/enhancements/pull/82)

**Security**

- [ ] [Pluggable Key/Cert Support for istio CA](https://github.com/istio/enhancements/pull/52)
- [ ] [Mutual TLS Migration](https://github.com/istio/enhancements/pull/83)
- [ ] [Certificate Management on Ingress Gateways](https://github.com/istio/enhancements/pull/51)
- [ ] [End User (JWT) Authentication](https://github.com/istio/enhancements/pull/42)

**Core**

- [ ] [Kubernetes: Envoy Installation and Traffic Interception](https://github.com/istio/enhancements/pull/55)
- [ ]  [Kubernetes: Istio In-Place Control Plane Upgrade](https://github.com/istio/enhancements/pull/45)




### **_List of PR’s that are ready to be merged(reviewed by feature owners/WG leads but needs a TOC member to approve):_**

- [ ]  [Basic Configuration Resource Validation](https://github.com/istio/enhancements/pull/46)
- [ ]  [WebAssembly Extension](https://github.com/istio/enhancements/pull/30)
- [ ]  [Locality Loadbalancing](https://github.com/istio/enhancements/pull/28)
- [ ]  [Resilience features: timeouts, retries, connection pools, outlier detection](https://github.com/istio/enhancements/pull/59)
- [ ]  [Support for protocols for Ingress, Egress Gateway](https://github.com/istio/enhancements/pull/60)

Hope this helps. Thank you.
