### ISSUE TITLE
Wasm API tracking issue

### ISSUE THREAD

**Issue by dgn** [istio/istio#35607]
Needed for 1.12:

- [x] api: Add WasmPlugin (https://github.com/istio/api/pull/1940)
- [x] Initial WasmPlugin implementation (https://github.com/istio/istio/pull/33374)
- [x] api: make WasmPlugin sha256 field non-optional. see https://github.com/istio/istio/pull/33374#discussion_r717028025 ( https://github.com/istio/api/pull/2125 and https://github.com/istio/istio/pull/35608)
- [x] add positive integration test for WasmPlugin (https://github.com/istio/istio/pull/35668)
- [x] use networkingutil.MessageToAny instead of gogo.MessageToAny in implementation. see https://github.com/istio/istio/pull/33374#discussion_r717026690 (https://github.com/istio/istio/pull/35628)
- [x] add support for ext-authz. current implementation behaves in unexpected ways when ext-authz is used. see https://github.com/istio/istio/pull/33374#discussion_r721807423
- [x] blog post(https://istio.io/latest/blog/2021/wasm-api-alpha/)
- [x] documentation(https://istio.io/latest/docs/tasks/observability/telemetry/)

Future:
- [x] ImagePullSecrets implementation(https://github.com/istio/istio/pull/37161)
- [ ] https://github.com/istio/istio/issues/32002

**Comment by mathetake** [comment]
How about "image pull secrets"? Is that removed from the scope of 1.12? cc @mandarjog @bianpengyuan

**Comment by dgn** [comment]
> If we get it in, that would be great. But it is not blocking .

+1 to that. I'll add it to the list

**Comment by mathetake** [comment]
and signature verification https://github.com/istio/istio/issues/32002 (cc @asraa) should also be tracked here

**Comment by mathetake** [comment]
https://github.com/istio/istio/pull/35683 this should also be merged in 1.12

**Comment by mathetake** [comment]
blog PR: https://github.com/istio/istio.io/pull/10530

**Comment by mathetake** [comment]
I realized that we haven't implemented "ImagePullPolicy" as well in imagefetcher.go https://github.com/istio/api/blob/master/extensions/v1alpha1/wasm.proto#L214

**Comment by mathetake** [comment]
anyone working on imagePullSecrets? (I won't be able to work neither on Istio or Envoy for a next few months or maybe a year, it would be great if someone can work on it)

**Comment by bianpengyuan** [comment]
I am working on it now, will also implement the pull policy.

**Comment by mathetake** [comment]
great! Thanks @bianpengyuan

**Comment by zirain** [comment]
not stale

**Comment by ingwonsong** [comment]
Image pull policy was added in 1.14!

**Comment by edieYoung** [comment]
Is ImagePullSecret released in 1.13?

**Comment by ingwonsong** [comment]
> Is ImagePullSecret released in 1.13?

No. 1.14 will enclose it.
