### ISSUE TITLE
Istio Scale & Performance

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#369]
Epic/Meta task to track scale & performance improvements in Istio.

Includes performance testing, benchmark/comparison, performance regression

**Comment by andraxylia** [comment]
Changed to P0 since this will be the focus in the next release.

**Comment by ldemailly** [comment]
We chatted a bit with @andraxylia and @costinm and there are several dimensions of testing we want to get to:

- [ ] longevity testing (long running test - checks for no leaks and ability to survive expiration of TTLs, pod movements, VM death, etc...). Under varying non 0 load.
- [ ] performance/throughput/latency test for small number of services and adapter (aka best case)
- [ ] performance as we increase the number of services

more tbd

**Comment by danehans** [comment]
Thoughts on porting this testing effort to Istio?

http://blog.kubernetes.io/2015/11/one-million-requests-per-second-dependable-and-dynamic-distributed-systems-at-scale.html

**Comment by danehans** [comment]
@andraxylia let me clarify myself. The k8s test above is simply a reference example. For Istio scale and performance, I was thinking of a similar test that would verify how the system under test (i.e. Istio) would perform with a sample application handling 1 million requests per second. After the 1m RPS baseline is established, subsequent tests could be performed with different Istio features enabled such as mTLS, traffic shifting, tracing, etc..

**Comment by ldemailly** [comment]
@danehans please see the Performance & Scalability WG plans
https://github.com/istio/community/blob/master/WORKING-GROUPS.md#performance-and-scalability
and maybe participate in the weekly meetings with your suggestions ?

**Comment by andraxylia** [comment]
@danehans Your suggestion makes sense.

**Comment by ldemailly** [comment]
Over the last 6 months we did most of the work we planed and more, cc @jasmine-jaksic for tracking reminding items

**Comment by howardjohn** [comment]
All work on this epic has been closed, future perf/scale stuff is just using the area label
