### ISSUE TITLE
[Umbrella Issue] Replace workloadSelector with targetRef for waypoint-targeted AuthorizationPolicy

### ISSUE THREAD

**Issue by keithmattix** [istio/istio#45713]
**Describe the feature request**
Instead of using workload selector for AuthorizationPolicy, users should be able to specify a waypoint proxy's `Gateway` resource as the targetRef of an AuthorizationPolicy in keeping with Gateway API's [policy attachment](https://gateway-api.sigs.k8s.io/references/policy-attachment/) semantics. More details can be found in the 

**Describe alternatives you've considered**

#### Continue using workloadSelector

This could potentially work but requires costly label matching. Also, UX is awkward when Gateway has different semantics.

#### Leverage Kubernetes NetworkPolicy

This is actually my preferred long-term [solution](https://docs.google.com/document/d/1Lk1I1qB-XwVWFP0sVcIN5JMJZHjuF3j8lGWtUeDK6pY/edit#heading=h.niaaortmjs4x); we'd use NetworkPolicy as the L4 authz policy resource and Istio's AuthorizationPolicy would exclusively bind to waypoints and sidecars. However, the time required to add a serviceAccount seelctor NetworkPolicy is much longer than our desired Ambient timeline. 

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

#### Work Breakdown

- [x] https://github.com/istio/api/issues/2885
- [x] https://github.com/istio/istio/issues/46360
- [x] https://github.com/istio/istio/issues/46370

**Additional context**
[Design Doc](https://docs.google.com/document/d/1MaMdyIQdOwq7mGCVMYW56FED9HrkJa93Nd0S0zBwws4/edit)

**Comment by keithmattix** [comment]
All the sub-issues are complete!
