### ISSUE TITLE
Telemetry API - Promote to Beta - Status Tracker

### ISSUE THREAD

**Issue by kfaseela** [istio/istio#46720]
As per discussions with @zirain, below tasks still need to be completed before Beta status. Will be enhanced further based on TOC inputs.

**Sub-Tasks**

- [ ] Enhance documentation about Telemetry Usage
- [ ] Support [MetricDefinition](https://github.com/istio/istio/issues/42128) through TelemetryAPI
- [ ] guidance about how to migrate custom metrics from EnvoyFilter to Telemetry API.
- [ ] More e2e tests
- [ ] Add docs tests
- [x] https://github.com/istio/istio/issues/46653

**Comment by kfaseela** [comment]
cc @whitneygriffith

**Comment by whitneygriffith** [comment]
See also: [Drive Istio Telemetry API to Beta](https://docs.google.com/document/d/1oozEgNnlaZqHorCb4oUtlAu3ucxtny-PhqDYyddidPA/edit?usp=sharing) proposal

**Comment by imnmo** [comment]
> [ ] Enhance documentation about Telemetry Usage

To get data and content, I believe we need to target a Usage survey driven from the Istio community (comms could come from Istio twiiter, mailing list). The insights gained from the survey could then be utilized to identify and fill gaps in our existing documentation. Open for the thoughts around this @whitneygriffith @kfaseela

**Comment by whitneygriffith** [comment]
@kyessenov what are the missing e2e scenarios we would like to test for? It will be great if we can create issues for these.
