### ISSUE TITLE
Dual-stack : Promote to Alpha - Status Tracker

### ISSUE THREAD

**Issue by kfaseela** [istio/istio#47998]
This issue is just used to track the status of pending activities needed to promote Dual Stack support in Istio to Alpha.
Reference: https://github.com/istio/enhancements/blob/master/features/dual-stack-support.md

The following items need to be completed to have the promotion. Any new items that need to be tracked can be updated as and when required before we close this task.

- [x] https://github.com/istio/istio/pull/46860
- [x] https://github.com/istio/istio/pull/47022
- [x] https://github.com/istio/istio/pull/46745
- [X] https://github.com/istio/istio/pull/47040
- [x] https://github.com/istio/istio/pull/47114
- [x] https://github.com/istio/istio/pull/47050
- [x] https://github.com/istio/istio/pull/47381
- [x] https://github.com/istio/istio/pull/47432
- [x] https://github.com/istio/istio/pull/47525
- [x] https://github.com/istio/istio/pull/51279
- [x] https://github.com/istio/istio.io/pull/14193
- [x] https://github.com/istio/istio.io/pull/14257
- [x] https://github.com/istio/istio/issues/44043
- [x] https://github.com/istio/istio/issues/41462
- [x] https://github.com/istio/istio/pull/45578
- [x] https://github.com/istio/istio/pull/43892
- [x] https://github.com/istio/enhancements/pull/170
- [x] https://github.com/istio/istio/issues/48336
- [x] https://github.com/istio/istio/issues/46911
- [x] https://github.com/istio/istio/pull/48334
- [X] https://github.com/istio/istio/pull/49308
- [x] https://github.com/istio/istio/issues/49344
- [x] https://github.com/istio/istio/pull/51617
- [x]  https://github.com/istio/istio/pull/52314
- [x] https://github.com/istio/istio/pull/51606
- [ ] https://github.com/istio/istio/pull/51914
- [x] https://github.com/istio/test-infra/pull/5401
- [x] https://github.com/istio/istio/issues/51222
- [x] https://github.com/istio/istio/pull/51221
- [x] https://github.com/istio/istio/pull/50747
- [x] https://github.com/istio/ztunnel/pull/1166
- [x] https://github.com/istio/test-infra/pull/5420
- [x] https://github.com/istio/istio/pull/51844
- [ ] https://github.com/istio/istio/issues/52895

**Comment by kfaseela** [comment]
cc @jacob-delgado @zhlsunshine @adams-shaun

**Comment by jacob-delgado** [comment]
I recently closed https://github.com/istio/istio.io/pull/13355 as I didn't have time to finish it. Please feel free to use the content from the PR to add it.

I would personally add, either we should auto-detect dual-stack behavior or we should add a flag that enables the environment variable in the `values.yaml` / istioctl profile (a dual stack profile would be nice, but not necessary)

**Comment by zhlsunshine** [comment]
Hi @kfaseela, there are 2 PRs to fix dual stack bugs after we announced that the dual stack support for Istio is available, not sure are they should be list here?
https://github.com/istio/istio/pull/45578
https://github.com/istio/istio/pull/43892

**Comment by kfaseela** [comment]
> Hi @kfaseela, there are 2 PRs to fix dual stack bugs after we announced that the dual stack support for Istio is available, not sure are they should be list here? #45578 #43892

Added these two to the checklist

**Comment by kfaseela** [comment]
Adding https://github.com/istio/istio/issues/46911 to the list, as this seems to be a genuine failure for dualstack cases

**Comment by leosarra** [comment]
Please also add the PR #48334 to the list :)

**Comment by kfaseela** [comment]
> Please also add the PR #48334 to the list :)

Done!

**Comment by kfaseela** [comment]
Updated the list to include some additional modifications needed for the ingress test framework

**Comment by kfaseela** [comment]
@leosarra I think @zhlsunshine has moved to some other priority work internally, and was asking for help to get the pending items to closure

**Comment by leosarra** [comment]
@kfaseela Sure I will take care of it

**Comment by leosarra** [comment]
@kfaseela can you add this to the list #51279 ? :)

**Comment by kfaseela** [comment]
> @kfaseela can you add this to the list #51279 ? :)

Done, thanks @leosarra

**Comment by kfaseela** [comment]
@howardjohn thank you so much for all the reviews so far. All the sub tasks tracked under this item are now completed. Do you think I can start the documentation work to move dualstack to alpha?

**Comment by howardjohn** [comment]
Yeah +1 to driving dual stack to alpha. Thanks for all the great work here

**Comment by bleggett** [comment]
Do we want to include `ambient` here at all, or is this purely for sidecar IPv6 support?

**Comment by kfaseela** [comment]
> Do we want to include `ambient` here at all, or is this purely for sidecar IPv6 support?

I can add all the tasks we did for ambient dualstack to the list here. or do we want to track that separately?

**Comment by leosarra** [comment]
I think we can add it here
