### ISSUE TITLE
Identify ambient integration tests gap comparing with sidecars

### ISSUE THREAD

**Issue by linsun** [istio/istio#48383]
Opening an issue based on discussion from ambient beta doc:

We need to identify if there are any tests we need for L4. Most of tests are for L7. May need to improve some of existing tests for L4. Need to identify owners.

**Comment by linsun** [comment]
@GregHanson do you have bandwidth to help with this?

**Comment by linsun** [comment]
related to https://github.com/istio/istio/issues/43698 but we want to understand the gaps and keep this as a living issue

**Comment by GregHanson** [comment]
can do

**Comment by GregHanson** [comment]
This is one of the more pressing issues in terms of L4 test coverage: https://github.com/istio/istio/pull/45988#issuecomment-1645762973

When ambient is the one initiating mtls (versus sidecar/gateway), the `X-Forwarded-Client-Cert` header is missing and test framework does not have a convenient way to verify mtls on the connection/request

@stevenctl 's sandwich work may provide a means when waypoint is involved in the request chain, but not guaranteed - and the feature may not arrive until after beta

**Comment by linsun** [comment]
Thanks Greg! Any other issues? Or is this the only gap?

**Comment by GregHanson** [comment]
Missing in ambient

Layer 4:

- [ ] TestMTLS is currently disabled: https://github.com/istio/istio/issues/48651
- [ ] TestPeerAuthtication: broken if source and dest are on same node and source is uncaptured.  Due to item above, only request success/failure tested, mTLS is connection is not verified: https://github.com/istio/istio/issues/43238
- [ ] TestAuthorizationL4: 
  - [ ] broken if source and dest are on the same node and source is uncaptured: https://github.com/istio/istio/issues/43238
  - [ ] missing `action` tests
- [ ] tlsOrigination test cases skipped: [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/traffic.go#L288)
- [ ] serverFirst test cases skipped: [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/traffic.go#L284)
- [ ] Telemetry: tests for prometheus exist but nothing else. [telemetry test feature list](https://github.com/istio/istio/blob/master/pkg/test/framework/features/features.yaml#L20)
- [ ] VirtualService.
  - [ ] TCPRoute is only tested at the gateway level, so test coverage does not exist for ambient and sidecar
  - [ ] similar for TLSRoute

Layer 7:

- [ ] TestAuthorizationL7: broken if source and dest are on the same node and source is uncaptured: https://github.com/istio/istio/issues/43238
- [ ] TestServerSideLB: broken if source and dest are on the same node and source is uncaptured: https://github.com/istio/istio/issues/43238
- [ ] TestTrafficSplit: broken if source and dest are on the same node and source is uncaptured: [TestTrafficSplit](https://github.com/istio/istio/issues/43238)
- [ ] VirtualService with multiple waypoint destinations fail: https://github.com/istio/istio/issues/44948: [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/routing.go#L872)
- [ ] Subset of Gateway tests skipped due to reliance on presence of `X-Envoy-Peer-Metadata` headers: [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/routing.go#L1188)
- [ ] roust host header test skipped due to reliance on `X-Forwarded-Client-Cert` header [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/traffic.go#L292)
- [ ] trafficLoop test cases skipped, waypoint->waypoint does not error: [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/traffic.go#L287)
- [ ] VirtualService
  - [ ] Mirroring?

Miscellaneous:

- [ ] TestServiceEntryDNS and TestOutboundPolicyAllowAny ServiceEntry tests are currently skipped
- [ ] TestServiceEntryDNSWithAutoAssign skipped https://github.com/istio/ztunnel/issues/582
- [ ] dns test cases skipped: https://github.com/istio/istio/issues/48614 [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/traffic.go#L298C5-L298C5)
- [ ] ExternalName support test cases skipped, relies on `X-Forwarded-Client-Cert` header: [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/traffic.go#L291)

**Comment by linsun** [comment]
Thank you Greg! I will go through each of item and open issues if needed.

**Comment by linsun** [comment]
Pinged @ilrudie to see if he could help with some of these testing gaps identified by Greg, focusing on L4 for now.

**Comment by ilrudie** [comment]
Is support for server first something we consider critical for Beta?

**Comment by linsun** [comment]
I'd say would be nice to have given this is an issue that ambient supposed to fix, but given sidecar doesn't have it yet, probably not as critical for the first pass.

Do you know why the server first test is skipped?

**Comment by ilrudie** [comment]
I didn't look too closely yet so not sure why it's skipped. I was just wondering if it was critical given the situation with sidecar. I agree it would be nice to have working and nice coverage but maybe less critical.

**Comment by ilrudie** [comment]
Seems like they're skipped because the implementation isn't working. Not sure the last time they were checked

**Comment by ilrudie** [comment]
- [ ] tlsOrigination test cases skipped: [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/traffic.go#L288)

It seems to me that this isn't something zt needs to handle. If the traffic is in mesh we want mTLS and otherwise we should use a gateway. I might be missing some context though so LMK if this line of thinking is fundamentally wrong.

**Comment by linsun** [comment]
> * [ ]  tlsOrigination test cases skipped: [test link](https://github.com/istio/istio/blob/master/tests/integration/pilot/common/traffic.go#L288)
> 
> 
> It seems to me that this isn't something zt needs to handle. If the traffic is in mesh we want mTLS and otherwise we should use a gateway. I might be missing some context though so LMK if this line of thinking is fundamentally wrong.

Looking at the test briefly, I think it may be used for connecting to external services.
