### ISSUE TITLE
Tracking bug: Reduce istio-agent binary size

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#48715]
Binary size directly leads to increased memory usage, slower container start, more expensive storage and bandwidth, etc.

Agent is particularly sensitive to this, as it is duplicated across many many instances

General details: https://blog.howardjohn.info/posts/go-binary-size/

Improvements to make

- [ ] https://github.com/istio/istio/pull/48704 2MB
- [ ] https://github.com/istio/istio/pull/48711 2MB
- [ ] https://github.com/envoyproxy/envoy/pull/31675 - I think this was 4MB
- [ ] https://github.com/istio/istio/pull/48717 - 2.5mb
- [ ] Remove `metav1` - 2.5mb
- [ ] Remove `gogo` protobuf entirely - 1.1mb

With all of the above improvements, the binary is dropped from 43MB to 28MB. This manifests as 11MB RSS usage of the agent, and 4MB k8s/cgroups reported memory usage of the sidecar container (cgroups and RSS report quite differently)
