### ISSUE TITLE
Ambient waypoint capture for service and workload work items

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#49438]
Implementation work items from https://github.com/istio/istio/issues/49032
- [x] WDS update to allow representation for svc-addressed waypoint capture
  - [x] https://github.com/istio/istio/issues/49435 (@MorrisLaw)
  - [x] https://github.com/istio/ztunnel/issues/816 (@MorrisLaw)
- [x] isito.io/use-waypoint capture impl
  - [x] https://github.com/istio/istio/issues/49436
  - [x] https://github.com/istio/ztunnel/issues/817
- [x] istioctl x waypoint updates https://github.com/istio/istio/issues/49437
- [x] implement istio.io/waypoint-for annotation #49851
- [x] refine svc-addressed waypoints https://github.com/istio/istio/issues/50005

Design Doc: [Ambient - Capture for Services and Workloads](https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit#heading=h.qntbxk5xx45)

**Comment by louiscryan** [comment]
@ilrudie 

Here's how I see the breakdown, feel free to adjust. I've updated the document to clearly categorize the feature into three distinct parts **Redirection**, **Binding** & **Generation**. Ill map tasks to each of those and define the ones that

- Redirection 
  - Basic "use-waypoint" annotation implementation to reference Gateway 
    - Service(s).  **High**
    - Pod / Deployment **High**
    - Namespace **High**
    - cross-namespace. **Med**
  - WDS update to model above (minimum for Istio built-in waypoints) **High**
  - ZTunnel update to implement redirection on client-side
    - To sandwiched **High**
    - To TLS-SNI  **Med**
    - To vanilla HTTP **Low**
  - Implement "waypoint-capture" to disable **High**
  - Implement non-stock Waypoint redirection (Gateway Status scraping per conformance). **Med**
     - Break this up by different **Binding** capability types
   - Implement for Egress with ServiceEntry **Med**
- Binding
  - Validate sandwich vs in-line HBONE for istio-waypoint (key production decision point) **High**
  - Demo of non-stock waypoint with manual configuration **Med**
  - Ztunnel to sandwiched Gateway binding,  ingress to waypoint. HTTP then TCP
    - Decap to PROXY protocol **High**
    - Decap to vanilla HTTP **Med**
    - Decap to free-bind **Low ?**
- Generation
  - Produce vanilla HTTP waypoint config that works with sandwich **High**
  - Demo of non-stock waypoint with generated config **Med**
  - MeshConfig for non-stock Gateway capability declaration for generation control **Low**
  - Demo variations ... **Low**

**Comment by howardjohn** [comment]
Still pending decision to do native HBONE vs sandwich for first launch of Istio impl. native HBONE is more expedient to ship, so we will start with that and evaluate sandwich to swap out the implementation when its ready and if its better.

For 'pluggable' implementation, we will start with simple HTTP case. This will be sandwich or unsandwiched -- this distinction is likely trivial, just a matter of whether the waypoint has redirection enabled or not (this _might_ need minor tweaks to **not** special-case the waypoint and respect the 'redirection enabled' aspect, but could also Just Work).

**Comment by ilrudie** [comment]
For the 1.22 release I think we can go ahead and mark this one as closed and create some follow ups for the future work/refinements/enhancements @louiscryan highlighted. @linsun @howardjohn, any objections?
