### ISSUE TITLE
V2 IP Autoallocation Controller - Feature Promotion Tracking

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#53596]
# Feature Stage

- [x] Feature released - 1.23
- [ ] Tracking feedback
- [ ] Installation API (HELM) - TBD
- [ ] Enabled By Default - 1.25 (for ambient only)

# Getting help

If you are having an issue with the feature and would like help or need to report a bug please open a separate issue and link it with this one for overarching tracking.

# Calling for feedback

If you have set `PILOT_ENABLE_IP_AUTOALLOCATE=true` feedback would be greatly appreciated.

Feedback template. Please copy this markdown into a comment and fill out if you would like to provide feedback. Please feel free to edit the comment if something changes and you would like to provide additional details.
```markdown
Istio Version:
Previous Version (if upgrading):
Data plane variant (select all that apply):

  - [ ] Sidecar
  - [ ] Ambient

Cluster/Mesh Size:
Upgrade Method (select one):

  - [ ] Revisioned
  - [ ] In-place

Installation Method:

  - [ ] Helm
  - [ ] Istioctl
  - [ ] Other (please specify)

Feedback:

  - Issues prior to upgrade:
  - Issues during upgrade:
  - Issues post-upgrade:
  - Additional comments:
```

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/53676 - partially opened link in a TODO in github

**Comment by chlunde** [comment]
Istio Version: 1.23.2
Previous Version (if upgrading):
Data plane variant (select all that apply):

  - [x] Sidecar
  - [ ] Ambient

Cluster/Mesh Size: Two clusters with ~1000 proxies each. ~2000 service entries with auto-generated IPs
Upgrade Method (select one):

  - [ ] Revisioned
  - [x] In-place

Installation Method:

  - [ ] Helm
  - [ ] Istioctl
  - [x] Other (please specify): `istioctl manifest generate` + flux

Feedback:

  - Issues prior to upgrade: Lots of random blackhole cluster blocks
  - Issues during upgrade: Some blackhole cluster during a one minute period. All auto-generated IPs changed.
  - Issues post-upgrade: None, running for 9 days now
  - Additional comments:

**Comment by ilrudie** [comment]
Thanks for the feedback @chlunde! Reviewing your notes I think this highlights a documentation gap. It's expected that IPs will change when swapping from the older ephemeral implementation to the new status-based implementation. We should make sure this is clearly called out.

**Comment by ilrudie** [comment]
https://github.com/istio/istio.io/pull/15931 closes the doc gap

Thank you @kfaseela for working on documentation!!!

**Comment by ilrudie** [comment]
not stale

**Comment by keithmattix** [comment]
Not stale
