### ISSUE TITLE
Metric Pruning - Feature Promotion Tracking

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#53836]
# Feature Stage

- [ ] Feature released
- [ ] Tracking feedback
- [ ] Installation API (HELM) - TBD
- [ ] Enabled By Default - TBD

# Getting help

If you are having an issue with the feature and would like help or need to report a bug please open a separate issue and link it with this one for overarching tracking.

# Calling for feedback

If you have enabled the following, your feedback would be greatly appreciated:

```
    METRIC_GRACEFUL_DELETION_INTERVAL: <duration>
    METRIC_ROTATION_INTERVAL: <duration>
```

Feedback template. Please copy this markdown into a comment and fill out if you would like to provide feedback. Please feel free to edit the comment if something changes and you would like to provide additional details.

```markdown
Istio Version:
Previous Version (if upgrading):
Data plane variant (select all that apply):

  - [ ] Sidecar
  - [ ] Ambient

Cluster/Mesh Size:
Upgrade Method (select one):

  - [ ] Revisioned
  - [ ] In-place

Installation Method:

  - [ ] Helm
  - [ ] Istioctl
  - [ ] Other (please specify)

Feedback:

  - Issues prior to upgrade:
  - Issues during upgrade:
  - Issues post-upgrade:
  - Additional comments:
```

**Comment by zirain** [comment]
i donot think that ztunnel support it.

**Comment by zirain** [comment]
not stale

**Comment by zirain** [comment]
not stale

**Comment by zirain** [comment]
not stale

**Comment by zirain** [comment]
this's not support any more, use https://github.com/istio/istio/pull/57736 instead.
