### ISSUE TITLE
1.24.1 tracking issue

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#53855]
- [x] https://github.com/istio/istio/issues/53849 **Regression** caused by setting privileged=false on the CNI plugin. Currently exploring options for a fix. Worst case, we can revert. Users can workaround by manually setting this currently.
  - [x] **Owner**: @jaellio . **ETA**: Monday 11/18
  - [x] https://github.com/istio/istio/pull/53888 Should resolve the AppArmor failures.
  - [x] Original PR had some issues, https://github.com/istio/istio/pull/53953/ resolves them
  - [x] Backport: https://github.com/istio/istio/pull/53970
- [x] https://github.com/istio/istio/issues/53843 **Regression** caused in part by setting privileged to false on the CNI plugin and failures on deleting non-existent IP table rules.
  - [x] https://github.com/istio/istio/pull/53888 Should resolve the AppArmor failures.
  - [x] https://github.com/istio/istio/pull/53951 - create a small PR to not fail if the raw table doesn't exist. (Owner: @jaellio)
  - [x] Backport: https://github.com/istio/istio/pull/53966
- [x] https://github.com/istio/ztunnel/issues/1360 **Upgrade issue** caused by not restarting workloads between CNI and Ztunnel upgrade (which we did not require or document). Ben is currently looking into some solutions here. Users can workaround by upgrading all workloads in the mesh after upgrading CNI but before upgrading Ztunnel. We added an upgrade note for this.
  - [x] Add upgrade notice for now (https://github.com/istio/istio.io/pull/15910)
- [x] https://github.com/istio/istio/issues/53847 **Regression** istioctl 1.24 cannot install on windows. We have a fix https://github.com/istio/istio/pull/53852, cherrypick https://github.com/istio/istio/pull/53856
- [x] (no issue currently) issue with non-existant backendRef with waypoint
  - [x] Owner: @keithmattix  , ETA: Tuesday 11/19
  - [x] PR: #53954
- [x] https://github.com/istio/istio/issues/53875 (fix: https://github.com/istio/istio/pull/53880, cherrypick https://github.com/istio/istio/pull/53930)
- [x] https://github.com/istio/istio/issues/53883 - revision upgrade causes issues
  - [x] Owner: @howardjohn, ETA: Monday 11/19
  - [x] Fix: https://github.com/istio/istio/pull/53935
  - [x] Backport https://github.com/istio/istio/pull/53963

**Nice to have**
* [x] https://github.com/istio/istio/issues/53846 DONE but missed 1.24.1 cutoff
  * [x] Upstream PR https://github.com/kubernetes-sigs/gateway-api/pull/3454
  * [x] Backport: https://github.com/kubernetes-sigs/gateway-api/pull/3465
  * [x] Import into Istio: https://github.com/istio/istio/pull/53993

Some issues moved to #53934 so that we can release regression fixes faster

**Comment by bleggett** [comment]
Linking https://github.com/istio/istio/pull/53153 and cc'ing @leosarra since he wants to wrap up and merge that PR and it's a prereq for https://github.com/istio/ztunnel/issues/1360

**Comment by zirain** [comment]
there's another regression from https://github.com/istio/proxy/pull/5825, `labels` missed after the refactor.

**Comment by ilrudie** [comment]
https://github.com/istio/istio/issues/53875, concurrency bug in istioctl install. Would be great to get it into 1.24.1 I think

**Comment by zirain** [comment]
> there's another regression from [istio/proxy#5825](https://github.com/istio/proxy/pull/5825), `labels` missed after the refactor.

there's a workaround, no more fix needed.

**Comment by leosarra** [comment]
>  PR TBD - create a small PR to not fail if the raw table doesn't exist. (Owner: @jaellio)

This one I already fixed in my PR https://github.com/istio/istio/commit/1b03f56e1476cf850afe11f70abdb15ed810e686
Shall I cherry-pick this small portion of the reconciliation PR to 1.24.1?

**Comment by keithmattix** [comment]
@leosarra Oh nice; that would be great! /cc @jaellio

**Comment by keithmattix** [comment]
Actually, I think @jaellio already has a PR somewhere; maybe they look ~the same?

**Comment by howardjohn** [comment]
Every critical fix has been merged!

**Comment by howardjohn** [comment]
This will be shipped this week
