### ISSUE TITLE
1.24.2 Tracking Issue

### ISSUE THREAD

**Issue by keithmattix** [istio/istio#53934]
Copying over some stuff from #53855 so we can get the regression fixes out

- [ ] https://github.com/istio/istio/issues/53843 **Longer term fix** Make iptables rules idempotent and reconcile them on startup
  - [ ] https://github.com/istio/istio/pull/53153 Should resolve the iptable failures.
- [ ] https://github.com/istio/ztunnel/issues/1360 **Upgrade issue** caused by not restarting workloads between CNI and Ztunnel upgrade (which we did not require or document). Ben is currently looking into some solutions here. Users can workaround by upgrading all workloads in the mesh after upgrading CNI but before upgrading Ztunnel. We added an upgrade note for this.
  - [ ] https://github.com/istio/istio/pull/53153 (prereq)
  - [ ] https://github.com/istio/istio/pull/53906 (startup reconcile)
- [x] https://github.com/istio/istio/issues/53846

**Needs triage**

**Not hard requirements for 1.24.2, as they are not regressions:**
- [x] https://github.com/istio/istio/issues/53593 Existing telemetry issue (owner: @keithmattix )
- [x] #53884 need to merge PeerAuthns in Ambient (owner: @keithmattix)
  - [x] PR:  #54073 
- [x] https://github.com/istio/istio/pull/53996

**Comment by ilrudie** [comment]
#54028 which fixes #54027 would be nice

**Comment by bleggett** [comment]
> https://github.com/istio/istio/issues/53843 Longer term fix Make iptables rules idempotent and reconcile them on startup

I don't believe this is related to either `privileged` or the (lack of) iptables reconciliation, I think it's a unique regression partially responsible for some recently-cropping-up CI flakes. Looking.

**Comment by YevhenLodovyi** [comment]
Hi, 

> https://github.com/istio/istio/issues/53884

I am really looking forward to this fix and as far as I can see it was not included in [1.24.2](https://istio.io/latest/news/releases/1.24.x/announcing-1.24.2/). Is there any chance it will be included in `1.24.3`?  It’s blocking me from using Ambient(

**Comment by keithmattix** [comment]
Ahh this was my fault; the fix merged but I didn't cherry pick the PR. So sorry about that! Yes it will be included in 1.24.3

**Comment by westwind-sc** [comment]
@keithmattix any proposed timeline for Istio `1.24.3`?

**Comment by keithmattix** [comment]
All items here have been completely or partially addressed. Closing
