### ISSUE TITLE
Full RawVM - Istio running on prem/on raw vms without k8s

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#541]
This is to track the follow up work from 0.2's #357 where the full istio stack runs on raw vm and not just the sidecar

**Comment by ldemailly** [comment]
- [X] Mixer, already runs on rawvm ( https://github.com/istio/istio/blob/master/devel/README.md#collection-of-scripts-and-notes-for-developing-for-istio ) but would neeed
- [ ] Mixer packaging/integration with rawvm builds
- [ ] Pilot
- [ ] Galley (k8s api server standalone)
- [ ] Some ingress?

**Comment by andraxylia** [comment]
The work for 0.2 is done, can you update the epic with the issues/PRs, and either close it or move it to 0.3 if there are items left?

**Comment by ldemailly** [comment]
it's already on 0.3 since it was created - again this is about no k8s at all

**Comment by costinm** [comment]
It appears people in community managed to validate this, and I don't expect additional work on this area until after 1.0, it can be reopen if there is interest.
