### ISSUE TITLE
Ambient Multi-Network Tracking Issue

### ISSUE THREAD

**Issue by keithmattix** [istio/istio#54245]
Now that the [design doc](https://docs.google.com/document/d/13c_r1doDCoRoEHuxk_eV8rnPi7X2pQgUWay9KMSSUrs/edit?tab=t.0#heading=h.ppr0kg59hrq3) is approved, we need to get working on implementation. We'll start with the protocol scope and then add the control plane/service discovery bits as they get approved.

- [x] istio/istio#54295
- [x] istio/ztunnel#1422
- [x] istio/istio#54306
- [ ] Add service hostname HBONE :authority support to sidecar servers
- [x] istio/ztunnel#1423
- [ ] istio/istio#55834 (post-alpha)
- [x] istio/istio#54883
- [ ] istio/istio#55451 (@keithmattix)
- [ ] Implement DNS proxy support for remote cluster reading (ztunnel and sidecar?) (post-alpha)
- [x] istio/api#3463
- [ ] istio/istio#55478 (@jaellio)
- [ ] istio/istio#56044 (@Stevenjin8)
- [ ] istio/istio#56228
- [ ] istio/istio#56047 (@Stevenjin8)
- [ ] istio/ztunnel#1555 (@krinkinmu)

**Comment by keithmattix** [comment]
Not stale

**Comment by kamalmarhubi** [comment]
This should probably be marked `lifecycle/staleproof`?

**Comment by keithmattix** [comment]
Alpha for multi network is released! Closing this issue
